### ISSUE TITLE
Compatibility list update

### ISSUE THREAD

**Issue by neomvll** [peterbuga/HASS-sonoff-ewelink#102]
First of all, thank you for the best component for sonoff users in HA. Now I can put my google-spreadsheet-broker in the trash :)

I have 2 sonoff RF 2.6.0, and works fine, so you can update the list to RF -> 2.6.0 -> yes

HA 92.1 / docker / RPi 3 B+

**Comment by gambalaya** [comment]
Here's another compatibility list update for this great component - my Sonoff 4ch Pro recently had a firmware upgrade to 3.0.1 and I can confirm it works fine (it is already in the list but there is no 3.0.1 firmware column yet).

HA 94.2 / virtualenv / RPi 2 B

**Comment by peterbuga** [comment]
thanks both, added 👍
