### ISSUE TITLE
Configuration invalid: Integration not found: Sonoff

### ISSUE THREAD

**Issue by Eiferer** [peterbuga/HASS-sonoff-ewelink#106]
I am sure what is wrong, I have imported the files into the file structure,
added only the required text into the configuration.yaml file.
I am pretty new to this so unsure what I have done wrong.

**Comment by peterbuga** [comment]
i don't know either ¯\_(ツ)_/¯

**Comment by clarm75** [comment]
I have the same situation, how can I configure Sonoff?

**Comment by shauncurtis-HA** [comment]
I am getting the same issue.
Everything completed as per instruction, but I get 'Integration Not Found'.
super frustrating - any help appreciated
