### ISSUE TITLE
Error during setup of component sonoff -  [Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by hughesba** [peterbuga/HASS-sonoff-ewelink#109]
Hi, this is my first issue report, so hope I am doing it right! 

I am getting the following error during HA start-up. I am running the latest version of HA - 0.92.2:

> Error during setup of component sonoff

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

> 

Any help would be greatly appreciated.

**Comment by fireinice** [comment]
I encounter the similar error today. but it seems work now. I think it's a temporary down by server side. Or the GFW do a wrong trick

**Comment by hughesba** [comment]
Thanks fireinice. It has been this way for a few days since I installed it, and have restarted a few times, but it has never worked for me. I suspect the issue is with contacting the eweLink server. I can use the eweLink app from the same home network so don't think it's a firewall problem. Hope someone can help me figure it out ...

**Comment by hughesba** [comment]
Ok, got it resolved. Commented out the region code and it worked out the region automatically.
