### ISSUE TITLE
Energy today and yesterday?

### ISSUE THREAD

**Issue by evlo** [peterbuga/HASS-sonoff-ewelink#110]
Does official api provide energy sum for today and yesterday like tasmota does? At least yesterday would be pretty useful for me to get. But maybe that would me reverse engineering original api for calendar/history/csv download and parsing it?

**Comment by peterbuga** [comment]
hi @evlo (sorry for late reply)
i have no idea if something like your request is possible. do you need it available & displayed somehow in HA or just a standalone type of requests in order to pull the data?

**Comment by evlo** [comment]
I wanted to have it displayed in HA, but since then I just gave up :D
