### ISSUE TITLE
Feature request: Support for updates via HACS

### ISSUE THREAD

**Issue by haakonstorm** [peterbuga/HASS-sonoff-ewelink#118]
https://github.com/custom-components/hacs

Thanks for a great piece of software. Works like a charm :)

**Comment by peterbuga** [comment]
related: https://github.com/peterbuga/HASS-sonoff-ewelink/pull/108#issuecomment-491325364 & https://github.com/peterbuga/HASS-sonoff-ewelink/issues/87
