### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by vcasado** [peterbuga/HASS-sonoff-ewelink#120]
Hi,

I'm using the latest version of HA (0.94.4). Following all the install instructions I'm getting this error:

**"The following components and platforms could not be set up": sonoff**

 What could I be doing wrong?

**Comment by peterbuga** [comment]
related to https://github.com/peterbuga/HASS-sonoff-ewelink/issues/122 will continue discussion there

**Comment by LW-Ho** [comment]
Hi,
i'm using the 0.96.3 version of HA, i'm getting this error, too.
and i downgrade version to fix issue?
