### ISSUE TITLE
Sonoff iFan03 vs Sonoff iFan02

### ISSUE THREAD

**Issue by bepece1** [peterbuga/HASS-sonoff-ewelink#123]
Sonoff iFan03 no work but Sonoff iFan02 yes, is different firmware?

**Comment by Lisheng2016** [comment]
my iFan03 works normally it creates four switches,one for the Light and three others for various of fan speeds
Firmware version:1.0.0

**Comment by bepece1** [comment]
how can I do it? Help me please 
Thanks

**Comment by peterbuga** [comment]
@bepece1 post the output of `sonoff_debug.py`

**Comment by peterbuga** [comment]
better support here https://github.com/peterbuga/HASS-sonoff-ewelink/issues/156
