### ISSUE TITLE
Home assistant can't restart

### ISSUE THREAD

**Issue by Gabber2222** [peterbuga/HASS-sonoff-ewelink#124]
I put everything as you said in configuration..yaml and in the folder custom_components. When I try to restart home assistant , I get this errors and It doesn't restart :

Error executing service <ServiceCall homeassistant.restart (c:0807283bd57f4011bd263a421d8363ff)>
23:04 loader.py (ERROR)
Error parsing manifest.json file at /config/custom_components/sonoff/manifest.json: Expecting value: line 7 column 1 (char 6)
23:04 loader.py (ERROR)

I have the latest version of hassio
Thank you

**Comment by hdjweb** [comment]
I have too same problem

**Comment by thostie2002** [comment]
I dont have the custom_component folder, how can i get it?

**Comment by sfgabe** [comment]
This also broke for me with the upgrade to 96 (or possibly the upgrade to Python 3.6 I did it at the same time). It seems like it doesn't want to load the component anymore.

**Comment by polyedre** [comment]
> I dont have the custom_component folder, how can i get it?

You need to create it. Use this file organisation (from the README) :

```
 custom_components
    └── sonoff
        └── __init__.py
        └── switch.py
        └── sensor.py
```

**Comment by thostie2002** [comment]
Where do i need to put that ?

**Comment by Gabber2222** [comment]
Does the component still Works in the latest home assistant ? It wont start with me ...




Thx




Outlook voor Android downloaden







On Mon, Jul 29, 2019 at 10:10 AM +0200, "polyedre" <notifications@github.com> wrote:














I dont have the custom_component folder, how can i get it?





You need to create it. Use this file organisation (from the README) :

 custom_components

    └── sonoff

        └── __init__.py

        └── switch.py

        └── sensor.py

**Comment by polyedre** [comment]
@thostie2002 you need to put the custom_components directory inside your config dir for Home Assistant. If you used pip to install it by default it is in the `.homeassistant` folder.
@Gabber2222 It seams that there is a problem with your `manifest.json` file, could you put it here ? I tried with this example and it worked:
```
{
  "domain": "your_domain_name",
  "name": "Your Integration",
  "documentation": "https://www.example.com",
  "dependencies": [],
  "codeowners": [],
  "requirements": []
}
```

**Comment by Gabber2222** [comment]
Dear Peterbuga,




I don 't understand what you mean with the manifest.json file. I copied it from the website.




Thx  in advance,




Ivan 






Outlook voor Android downloaden







On Mon, Jul 29, 2019 at 10:30 AM +0200, "polyedre" <notifications@github.com> wrote:












@thostie2002 you need to put the custom_components directory inside your config dir for Home Assistant. If you used pip to install it by default it is in the .homeassistant folder.

@Gabber2222 It seams that there is a problem with your manifest.json file, could you put it here ? I tried with this example and it worked:
{
  "domain": "your_domain_name",
  "name": "Your Integration",
  "documentation": "https://www.example.com",
  "dependencies": [],
  "codeowners": [],
  "requirements": []
}

**Comment by thostie2002** [comment]
So i need to make a new file in the config folder named custom_components?

@gabber2222 are you dutch?

**Comment by Gabber2222** [comment]
A new folder




Outlook voor Android downloaden







On Mon, Jul 29, 2019 at 11:02 PM +0200, "thostie2002" <notifications@github.com> wrote:












So i need to make a new file in the config folder named custom_components?


@Gabber2222 are you dutch?

**Comment by Gabber2222** [comment]
Yes, i am Dutch :-) 




Outlook voor Android downloaden







On Mon, Jul 29, 2019 at 11:02 PM +0200, "thostie2002" <notifications@github.com> wrote:












So i need to make a new file in the config folder named custom_components?


@Gabber2222 are you dutch?

**Comment by markbooker** [comment]
I have added the sofoff: section to my configuration.yaml file, and I have added the .py files to my config/custom_components/sonoff folder but I et the following error when checking the config from within HASS

Log Details (ERROR)
Tue Aug 13 2019 21:51:34 GMT-0700 (Pacific Daylight Time)
Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 355, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 28, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'

Any pointers to what I have done wrong?

**Comment by peterbuga** [comment]
@markbooker here https://github.com/peterbuga/HASS-sonoff-ewelink/issues/130

**Comment by markbooker** [comment]
@peterbuga thank-you, this resolved the issue, would it be possible to add that as a requirement or setup step to the page, I think it would help a lot of people.

**Comment by peterbuga** [comment]
@markbooker in a normal installation everything is added automatically upon first boot with this component enabled, who knows what kind of other problems you guys have around there :/

**Comment by macfarlaneb** [comment]
@peterbuga I think what @markbooker is suggesting is a great idea, as I know these constant websocket questions are tiring. If there was a simple step in the guide to ensure the pre-reqs are installed, your time won't be wasted. I can tell these posts frustrate you (there's a multitude of examples), so by ensuring the detail is available, and simple, for users to follow, it would reduce some of this angst.

**Comment by thostie2002** [comment]
i have it now working, the only thing is it changes often to unavailable but that stop when I switch how can I solve that?

**Comment by Oelus** [comment]
Docker image would be great.
