### ISSUE TITLE
dependence websocket

### ISSUE THREAD

**Issue by Maverik1408** [peterbuga/HASS-sonoff-ewelink#133]
hi, i copy file into .homeassistant inside custom_components folder, i reboot raspberry but receive errore dependance websocket

REQUIREMENTS = ['uuid', 'websocket-client==0.54.0']

i can resolve?

tnks.

**Comment by peterbuga** [comment]
https://github.com/peterbuga/HASS-sonoff-ewelink/issues/130#issuecomment-519064163
