### ISSUE TITLE
After last HA update state is not updated instantly

### ISSUE THREAD

**Issue by antoweb** [peterbuga/HASS-sonoff-ewelink#139]
Hi,
i have just updated HA to 0.98.5 and when i activate a sonoff from ewelink app the state in HA is not yet updated instantly. Before theha update, after 1 seconds the state was correctly udated in HA GUI.

**Comment by peterbuga** [comment]
downgrade

**Comment by antoweb** [comment]
downgrade is not a solution is a workaround

Il sab 28 set 2019, 12:31 Peter Buga <notifications@github.com> ha scritto:
