### ISSUE TITLE
no sonoff devices in home assistant

### ISSUE THREAD

**Issue by scatf-ha** [peterbuga/HASS-sonoff-ewelink#141]
Hello,
I have installed the latest version of hassio, added the sonoff lines to the configuration.yaml and copied the other files into the custom-folders. Restarted the server. However, I cannot see any sonoff device! Do you have any idea what might be wrong? Thanks a lot Frerk

**Comment by peterbuga** [comment]
duplicate https://github.com/peterbuga/HASS-sonoff-ewelink/issues/138
