### ISSUE TITLE
After last HA update the custom component cause some problem.

### ISSUE THREAD

**Issue by niccolobusato** [peterbuga/HASS-sonoff-ewelink#142]
I've noticed that after the last update my HA goes offline after dome time. if i disable your component in configuration.yaml everything works just fine. is that a real issue?

**Comment by peterbuga** [comment]
i need more than than, any logs?

**Comment by niccolobusato** [comment]
i've re-activated your component, then restarted HA, when i noticed the problem i copied the HAlog and now posted here. now my fronted is not working, only ssh, ftp and samba addon are still on.
[home-assistant.log](https://github.com/peterbuga/HASS-sonoff-ewelink/files/3623260/home-assistant.log)

**Comment by niccolobusato** [comment]
fixed with the last HA release (0.99.0)
