### ISSUE TITLE
Tried to follow instructions but nothing happening

### ISSUE THREAD

**Issue by kpmkpm** [peterbuga/HASS-sonoff-ewelink#144]
I have my HA installed on CentOS, and just got 4 of these new (DIY) sonoff basic r3, but since the first one did not work in DIY mode at all, I decided to just stay with the original firmware. The fw was updated to 3.3.0.

I tried to follow the instructions here and installed the python files into .homeassistant/custom\_components/sonoff/ folder and made following additions to my .homeassistant/configuration.yaml

&amp;amp;#x200B;

^(sonoff:)

^(username: my-username)

^(password: my-password)

^(scan\_interval: 60)

^(grace\_period: 600)

^(api\_region: 'eu')

^(entity\_prefix: True)

^(debug: False)

&amp;amp;#x200B;

I also tried debug: True, but no debug log was found (in .../custom\_components/sonoff/?). After reboot the home-assistant.log says

^(2019-09-26 15:06:21 WARNING (MainThread) ^(\[homeassistant.loader\] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.))

but this is just a warning and can be ignored? However, I thought this would automatically create the entities I have (and which can be seen with the [sonoff-debug.py](https://sonoff-debug.py)), but nothing seems to be visible in HA.

Did I miss something in the configuration or should FW 3.3.0 and Sonoff R3 basic (DIY) work at all with this integration?

The devices are working perfectly with the eWeLink app and also the Alexa and Google Home integration are working, but I would like to get them to be seen and controlled by HA, if possible, to make some automations and so on.

**Comment by peterbuga** [comment]
have you searched thoroughly in the devices list? sometimes they don't pop-out automatically in frontend like they used to in the old HA.
if still cannot find it, post the output of `sonoff-debug.py`

**Comment by kpmkpm** [comment]
Thanks for a quick reply. I am quite new with this HA and not sure what you mean with "search through deiveces list". I checked Configuration->Entity Registry and Developer Tools -> States, but at least there is no sign of anything about sonoff. Is there a list somewhere in the filesystem to check and manually have to add these devices?

This is the devices.json generated by sonoff-debug.py:

`[
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/Q4RJzznuKEeDgFXbgyS9OClbyEDR7gXd.png",
    "brandName": "SONOFF",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc:8080/api/detail/5c700fd5cc248c47441fd24a_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "5c4c1aee3a7d24c7100be054",
        "chipid": "00ABB387",
        "description": "20190508006",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-BD1-GL",
        "modelInfo": "5c700fd5cc248c47441fd24a",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7",
        "uiid": 1
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "alexa": [
          "944fa307-1f9f-4715-9ecb-6a610cd92fc8_26ca1996a20e8bd63617ab272d4eeede1d2d8e32"
        ],
        "gaction": [
          "944fa307-1f9f-4715-9ecb-6a610cd92fc8_ewelink-google-home-v1"
        ]
      },
      "controlType": 4,
      "fwVersion": "3.3.0",
      "init": 1,
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -40,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "on",
      "switch": "off",
      "version": 8
    },
    "productModel": "BASIC_R3",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 1,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "m_2fc8_kpm@": "on"
    },
    "type": "10",
    "uiid": 1
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/Q4RJzznuKEeDgFXbgyS9OClbyEDR7gXd.png",
    "brandName": "SONOFF",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc:8080/api/detail/5c700fd5cc248c47441fd24a_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "5c4c1aee3a7d24c7100be054",
        "chipid": "00B39E5A",
        "description": "20190508006",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-BD1-GL",
        "modelInfo": "5c700fd5cc248c47441fd24a",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7",
        "uiid": 1
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "alexa": [
          "4a6ef09e-1a0e-42e7-82d5-3f7eb0f23551_26ca1996a20e8bd63617ab272d4eeede1d2d8e32"
        ],
        "gaction": [
          "944fa307-1f9f-4715-9ecb-6a610cd92fc8_ewelink-google-home-v1"
        ]
      },
      "fwVersion": "3.3.0",
      "init": 1,
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -44,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "on",
      "switch": "off",
      "version": 8
    },
    "productModel": "BASIC_R3",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "m_2fc8_kpm@": "on"
    },
    "type": "10",
    "uiid": 1
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/Q4RJzznuKEeDgFXbgyS9OClbyEDR7gXd.png",
    "brandName": "SONOFF",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc:8080/api/detail/5c700fd5cc248c47441fd24a_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "5c4c1aee3a7d24c7100be054",
        "chipid": "007128FC",
        "description": "20190508006",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-BD1-GL",
        "modelInfo": "5c700fd5cc248c47441fd24a",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7",
        "uiid": 1
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "alexa": [
          "5c19e91d-4925-4d94-9d8b-27aff3400632_26ca1996a20e8bd63617ab272d4eeede1d2d8e32"
        ],
        "gaction": [
          "944fa307-1f9f-4715-9ecb-6a610cd92fc8_ewelink-google-home-v1"
        ]
      },
      "fwVersion": "3.3.0",
      "init": 1,
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -47,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "on",
      "switch": "off",
      "version": 8
    },
    "productModel": "BASIC_R3",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "m_2fc8_kpm@": "on"
    },
    "type": "10",
    "uiid": 1
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/Q4RJzznuKEeDgFXbgyS9OClbyEDR7gXd.png",
    "brandName": "SONOFF",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc:8080/api/detail/5c700fd5cc248c47441fd24a_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "5c4c1aee3a7d24c7100be054",
        "chipid": "00ABC01C",
        "description": "20190508006",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-BD1-GL",
        "modelInfo": "5c700fd5cc248c47441fd24a",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7",
        "uiid": 1
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "alexa": [
          "e8e67598-7b8b-4fb5-b15f-eeb445fe99a7_26ca1996a20e8bd63617ab272d4eeede1d2d8e32"
        ],
        "gaction": [
          "944fa307-1f9f-4715-9ecb-6a610cd92fc8_ewelink-google-home-v1"
        ]
      },
      "fwVersion": "3.3.0",
      "init": 1,
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -57,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "on",
      "switch": "off",
      "version": 8
    },
    "productModel": "BASIC_R3",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "m_2fc8_kpm@": "on"
    },
    "type": "10",
    "uiid": 1
  }
]
`

**Comment by kpmkpm** [comment]
I resetted all switches and configured them in EweLink again. After that they mysteriously appeared in the states listing from where I manually added to the UI. Thank you for your awesome work.

**Comment by peterbuga** [comment]
> After that they mysteriously appeared in the states listing

i'm a fan of magic too 😄 glad you sorted it out
