### ISSUE TITLE
sonoff T1 EU

### ISSUE THREAD

**Issue by rutenio** [peterbuga/HASS-sonoff-ewelink#16]
Hello. Before the last update, my Sonoff T1 EU touch 2-channel detected 4 switches. I ignored the last 2 and used the first 2. After the last update I could no longer use it because it tries to insert the 2 channels with the same ID, generating an error and only showing me 1 switch.

**Comment by rutenio** [comment]
These are the errors: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 343, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: switch.sonoff_10003a8ad1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 343, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: switch.sonoff_10003a8ad1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 343, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: switch.sonoff_10003a8ad1

**Comment by 2016for** [comment]
Please also send the sonoff-debug.py json
It could be that the uiid set by app and then trying to find out number of
switches might be causing the problem.

Thanks.

**Comment by 2016for** [comment]
@rutenio Check this out with the instructions:
https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug

You can use Terminal/cmd prompt on mac/pc with python installed.

Thanks.

**Comment by peterbuga** [comment]
@rutenio please update the files and give it another try, i just pushed a fix.

let me know if it's working now, thanks

**Comment by rutenio** [comment]
Hello @peterbuga . It's all gone back to the way it was before. The device with 2 switches is recognized with 4. But I disregard the last 2 and I can solve my problem, thank you.
