### ISSUE TITLE
Sonoff invalid config after 0.100.1 update

### ISSUE THREAD

**Issue by martusi61** [peterbuga/HASS-sonoff-ewelink#162]
When I restart after upgrading to Home Assistant 0.100.1 I get:

Invalid config
The following components and platforms could not be set up:
sonoff
Please check your config.

After a configuration check:

Component error: sonoff - cannot import name 'run_coroutine_threadsafe' from 'homeassistant.util.async_' (/usr/src/homeassistant/homeassistant/util/async_.py)

The sonoff switch is not available.

**Comment by naamah75** [comment]
Same issue here.

**Comment by superjasiek** [comment]
Same here :-( fortunately could rollback

**Comment by vasil-d** [comment]
same here

**Comment by Bettinaglio** [comment]
Install the new versions from here, install it in the custom_components/sonoff, and all will work as it should (done today, works like a charm).

**Comment by martusi61** [comment]
Peter Buga wrote me:

**“you need to upgrade the sonoff component to the latest version:
 GitHub
peterbuga/HASS-sonoff-ewelink
Simple Home Assistant component to control Sonoff/eWeLink smart devices - peterbuga/HASS-sonoff-ewelink
run_coroutine_threadsafe was removed from util.async_, the updated version now uses asyncio”**

I did it, I restarted and the problem was solved.

**Comment by primalnow** [comment]
@peterbuga 

I am trying to make use of https://github.com/skydiver/ewelink-api.

Seems this API is suffering from the same problem.  Can you please let me know what exactly was changed by EWLINK?

**Comment by peterbuga** [comment]
yes, something changed ;)

**Comment by primalnow** [comment]
Lol. How about letting me know in private, how to fix it? 😁 😁
