### ISSUE TITLE
POW R2 fw 3.3.1 doesn't connect

### ISSUE THREAD

**Issue by robbymazzoni** [peterbuga/HASS-sonoff-ewelink#164]
Configuration is the following
Hassio 0.100.2 - Sonoff POW R2 - Firmware 3.3.1
Please note that on the same network 4 CH e 4 CH PRO are working perfectly.
Any idea?

**Comment by peterbuga** [comment]
can you please give more details about the problem, meaning you don't see the POW R2 at all in HA? or are you experiencing stuck states like in here https://github.com/peterbuga/HASS-sonoff-ewelink/issues/128 (in which case i will close this issue and mark it as a duplicate)

as a small explanation it's quite impossible for a device previously working to not show up in HA when other are clearly working, try a few more reboots, make sure you have the latest version/code of the sonoff component, try to remove all the _pycache_ files and so on...
(you could also provide the output of `sonoff-debug.py` if the problem persists, but i'm quite sure i won't see anything problematic around there)

**Comment by robbymazzoni** [comment]
I don't see it at all in HA. It's a new item bought some days ago. Updated to firmware 3.3.1 today, I tried to cennect by restarting hassio (3 times) but I can't see it.
I confirm I have two separate account to access eWeLink.
Now, I will try to get some info from the log and then we will see,

**Comment by peterbuga** [comment]
@robbymazzoni sorry to hear that but without any logs or `sonoff-debug.py` there's not much i can do
also make sure you checked thoroughly in Developer area States section that the POW R2 is 100% *not* there (sometimes it fails to show up automatically in frontend and you have to manually add it)

**Comment by robbymazzoni** [comment]
> 

[
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/KRZ54OifuGmjoEMxT1YYM3Ybu2fj5K2C.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceStatus": "",
    "deviceUrl": "https://eu-api.coolkit.cc:8080/api/detail/5a2e1aee0cf772f92c342ef8_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "chipid": "00BE5C3F",
        "description": "WO1881999",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-B04-GL",
        "modelInfo": "5a2e1aee0cf772f92c342ef8",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u56db\u901a\u9053\u63d2\u5ea7",
        "uiid": 4
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "alexa": []
      },
      "configure": [
        {
          "outlet": 0,
          "startup": "off"
        },
        {
          "outlet": 1,
          "startup": "off"
        },
        {
          "outlet": 2,
          "startup": "off"
        },
        {
          "outlet": 3,
          "startup": "off"
        }
      ],
      "fwVersion": "3.3.0",
      "init": 1,
      "lock": 0,
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "pulse": "off",
      "pulseWidth": 0,
      "pulses": [
        {
          "outlet": 0,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 1,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 2,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 3,
          "pulse": "off",
          "width": 1000
        }
      ],
      "rssi": -30,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "switches": [
        {
          "outlet": 0,
          "switch": "off"
        },
        {
          "outlet": 1,
          "switch": "on"
        },
        {
          "outlet": 2,
          "switch": "on"
        },
        {
          "outlet": 3,
          "switch": "off"
        }
      ],
      "uiActive": 60,
      "version": 8
    },
    "productModel": "4CH",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedBy": {
      "permit": 15,
      "phoneNumber": "[hidden]",,
      "shareTime": 1559837647933
    },
    "showBrand": true,
    "tags": {
      "m_7c74_robe": "on"
    },
    "type": "10",
    "uiid": 4
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/KRZ54OifuGmjoEMxT1YYM3Ybu2fj5K2C.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceStatus": "",
    "deviceUrl": "https://eu-api.coolkit.cc:8080/api/detail/5a2e1af20cf772f92c342ef9_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "chipid": "00CD2A72",
        "description": "WO181882070",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-B04-GL",
        "modelInfo": "5a2e1af20cf772f92c342ef9",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u56db\u901a\u9053\u63d2\u5ea7",
        "uiid": 4
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "configure": [
        {
          "outlet": 0,
          "startup": "stay"
        },
        {
          "outlet": 1,
          "startup": "stay"
        },
        {
          "outlet": 2,
          "startup": "stay"
        },
        {
          "outlet": 3,
          "startup": "stay"
        }
      ],
      "controlType": 8,
      "fwVersion": "3.3.0",
      "init": 1,
      "lock": 0,
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "pulse": "off",
      "pulseWidth": 0,
      "pulses": [
        {
          "outlet": 0,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 1,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 2,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 3,
          "pulse": "off",
          "width": 1000
        }
      ],
      "rssi": -43,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "switches": [
        {
          "outlet": 0,
          "switch": "off"
        },
        {
          "outlet": 1,
          "switch": "off"
        },
        {
          "outlet": 2,
          "switch": "off"
        },
        {
          "outlet": 3,
          "switch": "off"
        }
      ],
      "uiActive": 60,
      "version": 8
    },
    "productModel": "4CH Pro",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedBy": {
      "permit": 15,
      "phoneNumber": "[hidden]",,
      "shareTime": 1559837615362
    },
    "showBrand": true,
    "tags": {
      "m_7c74_robe": "on"
    },
    "type": "10",
    "uiid": 4
  }
]

>

**Comment by robbymazzoni** [comment]
@peterbuga as you can see only 2 items are on the network. I grant you that the POW R2 is on and online

**Comment by peterbuga** [comment]
i have to honest say... this truly s*cks :|
as you mentioned above, as long as the output above doesn't display 3 devices you won't see it either in HA, very odd indeed and i strongly suspect itead is taking steps into making this component to stop working (can't blame them :)) )

if the problem persists and more cases start showing up (it's hard to tell if it's just you) i might be able to implement an option to force inject a device into HA through configuration but the current problems with POW R2 not reporting the usage values anymore the best you'll have would be just the on/off option.

as a test try to use the main ewelink account in HA config, maybe the sharing was not completed successfully or something, try to take the device offline for a couple of times, try anything you can think off

also, the ewelink app is highly depended on the output above, without it you should see the device missing there too

**Comment by robbymazzoni** [comment]
I'll try all of them. Another couple of tests and, if no response, no doubt I will go on Tasmota. I'll let u know tomorrow

**Comment by peterbuga** [comment]
@robbymazzoni try to connect also with the 2nd shared devices account in eWeLink app and see if all the devices are showing up there too (which i hardly doubt, as I mentioned above the devices presented to you are based on the output above)

**Comment by robbymazzoni** [comment]
@peterbuga just answering now. Using standard account POW is shown by sonoff-debug. I'll test with HA

**Comment by robbymazzoni** [comment]
![POW](https://user-images.githubusercontent.com/52409624/66737196-9a59d280-ee6b-11e9-97b7-eaabad181a06.png)

Here it is; I confirm that if I log on the App Ewelink with my mirror account POW is not shown.

**Comment by peterbuga** [comment]
well it sounds like a no-brainer to me, it's not a component problem it's more like an account/shared device problem. 
i suggest to delete the mirror account (or remove all the devices from it) and re-do everything again... if you still want to keep the cloud accessibility or go tasmota way 💪 if you have this option

**Comment by robbymazzoni** [comment]
I agree with you @peterbuga: account problem. I'll keep the POW original because I don't need to access it via app and starting a new tool like Tasmota and MQTT would be quite boring.
If I find something new, I'll let you know.
Thanks and ciao
