### ISSUE TITLE
Time expression never " "matches!"

### ISSUE THREAD

**Issue by fiservedpi** [peterbuga/HASS-sonoff-ewelink#166]
home-assistant.log](https://github.com/home-assistant/home-assistant/files/3720151/home-assistant.log)

Home Assistant release with the issue:
0.100.0
Frontend -> Developer tools -> Info: Frontend version: 20191002.2 - latest

Last working Home Assistant release (if known):
0.99.3

Operating environment (Hass.io/Docker/Windows/etc.):
Unraid Nvidia 6.7.2 /Docker/Home Assistant 0.100.0
Please provide details about your environment.
Unraid Nvidia 6.7.2 /Docker/Home Assistant 0.100.0

Integration:
sonoff custom component
Please add the link to the documentation at https://www.home-assistant.io/integrations/ of the integration in question.
-->
https://github.com/peterbuga/HASS-sonoff-ewelink

Description of problem:
Log Details (ERROR)

Error doing job: Exception in callback async_track_utc_time_change.<locals>.pattern_time_change_listener(<Event time_c....001100-04:00>) at /usr/src/homeassistant/homeassistant/helpers/event.py:402```

``` 
**Traceback:** (if applicable):```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 411, in pattern_time_change_listener
    calculate_next(now)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 395, in calculate_next
    localized_now, matching_seconds, matching_minutes, matching_hours
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 256, in find_next_time_expression_time
    raise ValueError("Cannot find a next time: Time expression never " "matches!")
ValueError: Cannot find a next time: Time expression never matches!
```

**Comment by fiservedpi** [comment]
https://github.com/home-assistant/home-assistant/issues/27522

**Comment by peterbuga** [comment]
this is definitely *not* a problem related to this component, looks more like some lib mismatches on your side or maybe a clock sync problem (really hard to tell, but clearly not related to this)

**Comment by fiservedpi** [comment]
got it hank you just realized it works perfectly on my other dev instance thank you for this
