### ISSUE TITLE
Sonoff integration

### ISSUE THREAD

**Issue by hantrax** [peterbuga/HASS-sonoff-ewelink#167]
I have donwloaded the last version, I  have insert code in configuration.yaml, copy file in custom_components and restart homeassistant. 
When I check configuraion, I receive this error:
Component error: sonoff - Integration 'sonoff' not found.
i try it with Home assistant 0.100.2 and 0.100.0

**Comment by peterbuga** [comment]
double check - you probably didn't follow the install steps properly, check/paste error logs

**Comment by hantrax** [comment]
Hi

I have put your folder in \\192.168.2.200\homeassistant\custom_components\sonoff
And insert this code:

sonoff:
  username: mymail
  password: password
  scan_interval: 60 #(optional, lower values than 60 won't work anymore!)
  grace_period: 600 #(optional)
  api_region: 'eu' #(optional)
  entity_prefix: False #(optional)
  debug: False #(optional)

2019-10-16 11:27:03 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: sonoff - Integration 'sonoff' not found. 2019-10-16 12:00:21 WARNING (MainThread) [homeassistant.components.http] Configuring api_password via the http integration has been deprecated. Use the legacy api password auth provider instead. For instructions, see https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password 2019-10-16 12:00:22 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff. Make sure all dependencies are installed
Inviato da Posta per Windows 10

Da: Peter Buga
Inviato: mercoledì 16 ottobre 2019 12:57
A: peterbuga/HASS-sonoff-ewelink
Cc: hantrax; Author
Oggetto: Re: [peterbuga/HASS-sonoff-ewelink] Sonoff integration (#167)

double check - you probably didn't follow the install steps properly, check/paste error logs

**Comment by peterbuga** [comment]
you need to remove everything that's after a **#** (hashtag) meaning:
```
sonoff:
  username: mymail
  password: password
  scan_interval: 60
  grace_period: 600
  api_region: 'eu'
  entity_prefix: False
  debug: False
```

**Comment by hantrax** [comment]
Nothing to do
When i check configuration I receive the error

Inviato da Posta per Windows 10

Da: Peter Buga
Inviato: mercoledì 16 ottobre 2019 13:04
A: peterbuga/HASS-sonoff-ewelink
Cc: hantrax; Author
Oggetto: Re: [peterbuga/HASS-sonoff-ewelink] Sonoff integration (#167)

you need to remove everything that's after a # (hashtag) meaning:
sonoff:
  username: mymail
  password: password
  scan_interval: 60
  grace_period: 600
  api_region: 'eu'
  entity_prefix: False
  debug: False

**Comment by peterbuga** [comment]
then i don't know what is the problem

**Comment by peterbuga** [comment]
@CVAS7 what exactly you are running ? give (ample) more details

**Comment by hantrax** [comment]
Hi Peter..
I have found this in the log:

File "/home/homeassistant/.homeassistant/customcomponents/sonoff/_init.py", line 28, in <module> import websocket ModuleNotFoundError: No module named 'websocket'

Any idea?

Inviato da Posta per Windows 10

Da: Peter Buga
Inviato: mercoledì 16 ottobre 2019 13:56
A: peterbuga/HASS-sonoff-ewelink
Cc: hantrax; Author
Oggetto: Re: [peterbuga/HASS-sonoff-ewelink] Sonoff integration (#167)

then i don't know what is the problem

**Comment by peterbuga** [comment]
@hantrax see https://github.com/peterbuga/HASS-sonoff-ewelink/issues/173

**Comment by hantrax** [comment]
Hi Peter

Thanks a lot!!
Now work!!!!!

Inviato da Posta per Windows 10

Da: Peter Buga
Inviato: lunedì 28 ottobre 2019 12:48
A: peterbuga/HASS-sonoff-ewelink
Cc: hantrax; Mention
Oggetto: Re: [peterbuga/HASS-sonoff-ewelink] Sonoff integration (#167)

@hantrax see #173

**Comment by CVAS7** [comment]
> @CVAS7 what exactly you are running ? give (ample) more details

I am trying to get the device status from ewelink login account (which has Sonoff Basic-1,SONOFF® Dual Channel -2) is created from ios,
Login is successful but , at or rt fails and following error is displayed.

Code taken from "HASS-sonoff-ewelink/sonoff-debug/sonoff-debug.py"

it was wokring perfcefly fine for a day, later and now I am getting  below error:

tried chaging the password , stiil it does not work.
===================
app_details {'at': '0e9798a8b20bddf4f846cb7d5a7cf5e710991724', 'rt': '36bda205a9765c9aa0608feffd9f21dbbbc9a5f7', 'user': {'_id': '5be99360537316dea64dcada', 'email': 'XXXXXXXXXXX', 'password': 'XXXXXXXXXXXXXXXXXXXXX', 'appId': 'oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq', 'createdAt': '2018-11-12T14:51:12.879Z', 'apikey': '163a6edc-b8d6-48b5-8ea6-0c8a3dcbee3e', '__v': 0, 'lang': 'en', 'online': False, 'onlineTime': '2019-10-27T15:12:33.745Z', 'ip': '122.172.146.195', 'location': '', 'offlineTime': '2019-10-27T15:13:12.075Z', 'userStatus': '2', 'appInfos': [{'os': 'ios', 'appVersion': '3.12.0'}]}, 'region': 'as'}
user_details {'at': '0e9798a8b20bddf4f846cb7d5a7cf5e710991724', 'rt': '36bda205a9765c9aa0608feffd9f21dbbbc9a5f7', 'user': {'_id': '5be99360537316dea64dcada', 'email': 'XXXXXXXXXXXXXXXXX', 'password': 'XXXXXXXXXXXXXXXXXXXXX', 'appId': 'oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq', 'createdAt': '2018-11-12T14:51:12.879Z', 'apikey': '163a6edc-b8d6-48b5-8ea6-0c8a3dcbee3e', '__v': 0, 'lang': 'en', 'online': False, 'onlineTime': '2019-10-27T15:12:33.745Z', 'ip': '122.172.146.195', 'location': '12.2324', 'offlineTime': '2019-10-27T15:13:12.075Z', 'userStatus': '2', 'appInfos': [{'os': 'ios', 'appVersion': '3.12.0'}]}, 'region': 'as', 'nickname': 'eWelink'}
headers {'Content-Type': 'application/json', 'Authorization': 'Bearer 0e9798a8b20bddf4f846cb7d5a7cf5e710991724'}
{
  "error": 400,
  "msg": "params incomplete"
}

**Comment by peterbuga** [comment]
@CVAS7 i'm sorry but i have no idea what's wrong in your case, just try to update to latest version of the component & in the same time you might have to accept that due to various (network) configurations / geolocation this component will simply not work for everyone 😞

**Comment by CVAS7** [comment]
> @CVAS7 i'm sorry but i have no idea what's wrong in your case, just try to update to latest version of the component & in the same time you might have to accept that due to various (network) configurations / geolocation this component will simply not work for everyone

Hello Peter , Thank a lot for your time,
Any Solution can be taken for ewelink or coolkit api, if so can you help me with contact or links
