### ISSUE TITLE
wrong credentials error with cn phone account

### ISSUE THREAD

**Issue by Trace-star** [peterbuga/HASS-sonoff-ewelink#168]
[custom_components.sonoff] Login failed! Please check credentials!

sonoff:
  username: '+86134'
  password: '13453'
  scan_interval: 60
  grace_period: 600
  api_region: 'as'
  entity_prefix: True
  debug: False

**Comment by Lisheng2016** [comment]
```

sonoff:
  username: 'your phone number without country code +86'
  password: '13453'
  scan_interval: 60
  grace_period: 600
  api_region: 'as'
  country_code: '86'
  entity_prefix: True
  debug: False
```

This should work

**Comment by peterbuga** [comment]
@Lisheng2016 there is no “country_code” configuration option, stop spreading false fixes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by difelice** [comment]
This might be related to [API "as" host down](https://github.com/peterbuga/HASS-sonoff-ewelink/issues/169).

**Comment by peterbuga** [comment]
@Trace-star you still have the same problem? can you login in the mobile app?

**Comment by a843161264** [comment]
I have the same trouble.
