### ISSUE TITLE
Hello, this plugin is great (unable to login using phone number)

### ISSUE THREAD

**Issue by liubo-chongqing** [peterbuga/HASS-sonoff-ewelink#17]
Hello, this plugin is great. However, I am not a programmer.What do I need to do to get him to work.
I have done this now.
configuration.yaml:
sonoff:
  username: +86xxxxxxxxxx（ewelink username）
  password:  00000000（ewelink password）
  scan_interval: 60 
  grace_period: 600 
  api_region: cn  

Download your PY Added in the directory 《custom_components》
custom_components：
---sonoff.py
---switch

Restart HA
Log Details (ERROR)
Wed Dec 12 2018 11:16:32 GMT+0800 (中国标准时间)

Couldn't authenticate using the provided credentials!

What else do I need to do to get him to display the switch and use him normally?

Test run the command in the Raspberry Pi home/pi/home assistant/custom_components/sonoff-debug directory
pi@raspberrypi:~/.homeassistant/custom_components $ ls
__pycache__  sonoff-debug  sonoff.py  switch
pi@raspberrypi:~/.homeassistant/custom_components $ cd sonoff-debug
pi@raspberrypi:~/.homeassistant/custom_components/sonoff-debug $ python sonoff-debug.py '+86xxxxxxxxx' 'xxxxxxxxx' > devices.json
Traceback (most recent call last):
  File "sonoff-debug.py", line 90, in <module>
    devices_json = get_devices()
  File "sonoff-debug.py", line 69, in get_devices
    headers.update({'Authorization' : 'Bearer ' + user_details['at']})
KeyError: 'at'
pi@raspberrypi:~/.homeassistant/custom_components/sonoff-debug $

**Comment by liubo-chongqing** [comment]
Thank you for your reply，I use Google Translate to communicate with you. I hope you can understand what I mean, my English is not good.I am very willing and testing to use this plugin, I don't want to rewrite the firmware to my SONOFF. But I am not a programmer and may not be able to help you. I can only find out how to use this plugin here.
I can share my ewelink phone username and password for you, you can test

**Comment by liubo-chongqing** [comment]
Thank you for your reply, I am very happy to test and use this plugin because I don't want to replace the firmware. if you need,
I can share my ewelink phone username and password for you and you can test it. I am not a programmer, I don't know if I can help you. I can only get the songoff access to HA normally.

**Comment by fireinice** [comment]
the phone number should be surround by sigle quote， otherwise the leading plus symbol would be trimmed by the home assistant

**Comment by fireinice** [comment]
username: '+86xxxxxxxxxx'（ewelink username）
password: 00000000（ewelink password）
scan_interval: 60
grace_period: 600
api_region: 'cn'

**Comment by liubo-chongqing** [comment]
Just saw the device。Thank you

If it is a sensor, or a light that can change color, does it automatically appear? Or need me to configure, configuration has no template reference

**Comment by 2016for** [comment]
Seems like it was just a "formatting" issue, please close this issue, if it is working for you now.
Thanks. 

Also,
@liubo-chongqing Currently only switches are supported.
However if there are other devices in your ewelink account, please send the sonoff-debug.py json details so that we can look into integrating those devices.

However the amazing man @peterbuga may not be available during the holiday season, so expect updates in January probably! :)
