### ISSUE TITLE
Working with Sonoff Basic R3

### ISSUE THREAD

**Issue by sjdvda** [peterbuga/HASS-sonoff-ewelink#172]
I am happy to report that I've been using this custom component with 4 [Sonoff Basic R3](https://www.itead.cc/sonoff-basicr3-wifi-diy-smart-switch.html) switches for the last 3 weeks and I have not run into any issues so far. Perhaps this could be added to the compatibility table?

**Comment by peterbuga** [comment]
hi @sjdvda thanks for reaching out!
i’m updating the compatibility list based on real working reportings (as you just did 👍)

would you be kind enough to mention the fw version(s) too? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sjdvda** [comment]
Hi Peter, all 4 are on firmware 3.3.0.

**Comment by peterbuga** [comment]
thanks 👍 i'll add it
