### ISSUE TITLE
bound method Sonoff.on_message of

### ISSUE THREAD

**Issue by Tomelin** [peterbuga/HASS-sonoff-ewelink#175]
Hi,

I have problem with HA and sonoff.  The problem occurs when I trigger ewelink by APP and the logs HA report this:

2019-11-07 17:47:20 ERROR (Thread-2) [websocket] error from callback <bound method Sonoff.on_message of <custom_components.sonoff.Sonoff object at 0x7f4e3c538c50>>: string indices must be integers
2019-11-07 17:47:22 ERROR (Thread-2) [websocket] error from callback <bound method Sonoff.on_message of <custom_components.sonoff.Sonoff object at 0x7f4e3c538c50>>: string indices must be integers

The line is each trigger by ewelink APP.  After a few seconds return this error:

2019-11-07 17:50:31 ERROR (Thread-2) [custom_components.sonoff] websocket error: Connection is already closed.

When return the error above, the interface HA return devices with: **Unavailable**.

The devices in HA just return working if restart service HA.

My HA working with docker (homeassistant/home-assistant:stable)

Sonoff version firmware: 3.3.0
Version HASS-sonoff-ewelink, lasted, I test today.

**Comment by peterbuga** [comment]
do you have a 2nd eWeLink shared account?

**Comment by Tomelin** [comment]
Yes, I do.

I configured my equipment by eWeLink and my wife uses by app eWeLink.

**Comment by peterbuga** [comment]
i'm sorry but i don't know what might be the problem, have you considered to install HA app and use that instead of using ewelink app in parallel?

**Comment by peterbuga** [comment]
@Tomelin i think i was able to replicate the above message (by mistake) and it was because the same account was used for HA and as well for eWeLink app, can you double check you're 100% using 2 different accounts for HA and mobile app?

**Comment by Tomelin** [comment]
@peterbuga I use the same account for HA and eWelink app.

I use the same account for authentication in eWelink and HA for sync between both.

**Comment by peterbuga** [comment]
@Tomelin you’re contradicting yourself, you just admited above that you have 2 accounts now only 1.
read the project’s description in full, create the 2nd account and the error will go away!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
