### ISSUE TITLE
Sonoff Pow R2 with power measurements

### ISSUE THREAD

**Issue by SergeyAnokhin** [peterbuga/HASS-sonoff-ewelink#18]
My output

    [
      {
        "__v": 0,
        "_id": "[hidden]"
        "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "brandName": "Sonoff",
        "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
        "deviceStatus": "",
        "deviceUrl": "",
        "deviceid": "[hidden]"
        "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "extra": {
          "_id": "[hidden]"
          "extra": {
            "apmac": "xx:xx:xx:xx:xx:xx",
            "brandId": "58e5f344baeb368720e25469",
            "description": "WO1818609",
            "mac": "xx:xx:xx:xx:xx:xx",
            "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
            "model": "PSC-B67-GL",
            "modelInfo": "5a2e1ae50cf772f92c342ef6",
            "ui": "\u529f\u7387\u68c0\u6d4b\u63d2\u5ea7\u8fc7\u8f7d\u544a\u8b66",
            "uiid": 32
          }
        },
        "group": "",
        "groups": [],
        "ip": "[hidden]"
        "location": "",
        "name": "[hidden]",
        "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
        "online": true,
        "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
        "params": {
          "alarmCValue": [
            -1,
            15
          ],
          "alarmPValue": [
            -1,
            -1
          ],
          "alarmType": "c",
          "alarmVValue": [
            -1,
            -1
          ],
          "current": "0.04",
          "endTime": "xxxx-xx-xxxxx:xx:xx.xxx",
          "fwVersion": "2.7.0",
          "hundredDaysKwh": "get",
          "init": 1,
          "oneKwh": "get",
          "power": "1.57",
          "rssi": -49,
          "staMac": "xx:xx:xx:xx:xx:xx",
          "startTime": "xxxx-xx-xxxxx:xx:xx.xxx",
          "startup": "stay",
          "switch": "on",
          "timeZone": 1,
          "voltage": "231.86"
        },
        "productModel": "Pow_R2",
        "settings": {
          "alarmNotify": 1,
          "opsHistory": 1,
          "opsNotify": 0
        },
        "sharedTo": [],
        "showBrand": true,
        "type": "10",
        "uiid": 32
      }
    ]

**Comment by SergeyAnokhin** [comment]
Finally, I added 

https://github.com/SergeyAnokhin/HASS-sonoff-ewelink/commit/cd3cec0e22c8a7c2669c20b3614dad65d8d61176 

sonoff.py
Line 386
`    def get_state(self):
        device = self.get_device()

        # Pow & Pow R2:
        if 'power' in device['params']: 
            self._attributes['power'] = device['params']['power']
        # Pow R2 only:
        if 'current' in device['params']: 
            self._attributes['current'] = device['params']['current']
            self._attributes['voltage'] = device['params']['voltage']
`

and its works for Pow & Pow R2 (tested). Basic model works also

**Comment by peterbuga** [comment]
@SergeyAnokhin can you please try this `sensors` branch (https://github.com/peterbuga/HASS-sonoff-ewelink/tree/sensors) and let me if you get new sensor entities inside HA? for the device/dump above this should create 3 new (current, power, voltage) sensors 

NOTICE in current state this branch is **highly likely** to throw some errors :sweat_smile: because I'm still on the road and I haven't/can't test it at all but it will be a great help for me if you could reply back with any error messages! this way i can move forward faster

**Comment by peterbuga** [comment]
someone else reported the sensors to work properly with this version [https://github.com/peterbuga/HASS-sonoff-ewelink/releases/tag/v0.2.0](https://github.com/peterbuga/HASS-sonoff-ewelink/releases/tag/v0.2.0) 
feel free to reopen the issue if there any problem related to it, thanks.
