### ISSUE TITLE
compatibility columns

### ISSUE THREAD

**Issue by hfcheng66** [peterbuga/HASS-sonoff-ewelink#185]
What the columns with number (like 1.6, 3.3.0 etc) means?
I plan to buy this Sonoff Basic https://www.amazon.com/gp/product/B078GDFYTY/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1, but want to confirm it is supported so I can integrate it into HASS.

Thanks!

**Comment by peterbuga** [comment]
this is not a forum

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
