### ISSUE TITLE
Cannot run hass with HASS-sonoff-ewelink

### ISSUE THREAD

**Issue by a843161264** [peterbuga/HASS-sonoff-ewelink#187]
hass version
0.100.2

HASS-sonoff-ewelink version
v0.3.3

Stop at "INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.5 seconds." with no error.

**Comment by a843161264** [comment]
I replaced 0.3.3 with 0.3.2, and then the error became:
" ImportError: cannot import name 'run_coroutine_threadsafe' from 'homeassistant.util.async_' "

**Comment by peterbuga** [comment]
this usually happens when you've done an improper edit to configuration.yaml, try to use `master` or `dev` branch code.
