### ISSUE TITLE
When do check config after setup HA hangs

### ISSUE THREAD

**Issue by jonk999** [peterbuga/HASS-sonoff-ewelink#191]
I have just setup Home Assistant in Docker using this instruction: https://community.home-assistant.io/t/absolute-beginners-guide-to-installing-ha-on-intel-nuc-using-docker/98412
Am running Home Assistant 0.103.2

I have played around a little with both Hass.io and Home Assistant in the past. I have set it up in Docker and gotten almost all my components showing up. The last one I have to do are my Ewelink/Sonoff switches. The firmware on the switch (latest) doesn’t seem to be compatible with flashing Tasmota, etc.
I downloaded the files and created a custom_components folder under /srv/homeautomation/hass-config as that is where my configuration.yaml is located. Then as per the instructions, I created a sonoff folder under that.

I edited my configuration.yaml file as per the instructions, however when I clicked on check config I get the spinning disc indicating it is doing something, but it never progresses past that. I have left it for over 30min and it doesn’t seem to complete the checking of the config so I can reboot knowing it’s all good.
If I reboot the machine running HA in Docker, I then have to comment out the sonoff config in the configuration.yaml and reboot again before I can get back into HA.

Not sure if it's something to do with my install, or I have done something wrong when configuring this.

I'm seeing the following in the log:
  File "/config/custom_components/sonoff/__init__.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Doctype html invalid

Cheers.

**Comment by peterbuga** [comment]
download files as zip not from browser

**Comment by jonk999** [comment]
Thanks. I had downloaded the files initially using the 'raw' link.
Downloaded again using zip file and config check now passes.
