### ISSUE TITLE
The sonoff plug-in doesn't work today

### ISSUE THREAD

**Issue by gmshiwoge** [peterbuga/HASS-sonoff-ewelink#194]
The sonoff plug-in can't be used normally now. When the has trigger switch, the device still doesn't work

**Comment by peterbuga** [comment]
@gmshiwoge does it work today 😄 ?

**Comment by gmshiwoge** [comment]
websocket error: Connection is already closed.
Log prompt: after I submit the problem, the plug-in will work normally three hours later. It's amazing

**Comment by peterbuga** [comment]
@gmshiwoge follow this thread https://github.com/peterbuga/HASS-sonoff-ewelink/issues/190
