### ISSUE TITLE
Cannot install this addon and has error info list below

### ISSUE THREAD

**Issue by admChenYunf** [peterbuga/HASS-sonoff-ewelink#195]
**delete this template text while filling your issue/request but before that please check if:**
- do you have the latest version of the code in use? (this is a very common problem & fix that everyone ignores)
I never use this code, and first time try to install
- did you gave a quick look to the other issues to see if the issue is already reported? (otherwise i will close the issue without any response. it takes me good hours to develop & manage this plugin, you can take 3 minutes to do a quick reading)
This issue is not reported yet.

What i do is try to install this addon on homeassistant addon store, copy the url of responsitory and add, then show nothing. from the system log, it shows below
![1](https://user-images.githubusercontent.com/38202831/71500722-2d1de100-28a1-11ea-86b5-6991a4ac3c2a.png)
![2](https://user-images.githubusercontent.com/38202831/71500726-2f803b00-28a1-11ea-8aa6-0b39acb272f4.png)

19-12-27 03:41:16 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/peterbuga/HASS-sonoff-ewelink repository
19-12-27 03:41:25 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/4952a1e1/repository.json: [Errno 2] No such file or directory: '/data/addons/git/4952a1e1/repository.json'
19-12-27 03:41:25 WARNING (MainThread) [hassio.store.data] Can't read repository information from /data/addons/git/4952a1e1/repository.json

**Comment by peterbuga** [comment]
there are clear install steps in the projects page! this component does not (and probably never will) support HACS
