### ISSUE TITLE
Component error: sonoff - Integration 'sonoff' not found.

### ISSUE THREAD

**Issue by SuperSpe** [peterbuga/HASS-sonoff-ewelink#196]
I put the directory with python files inside "addons" and updated the configuration.yaml as need but this is the message when I restart hass.io

Component error: sonoff - Integration 'sonoff' not found.

**Comment by SuperSpe** [comment]
Should the sonoff directory must be on "config/custom_addons" instead?

**Comment by ashoktvm** [comment]
The files should be under custom_components not addons

**Comment by peterbuga** [comment]
there are clear instructions on main page on how to install it!

**Comment by JasperIrl** [comment]
Followed instructions and same error as above
