### ISSUE TITLE
Allow sonoff items to be assigned to areas

### ISSUE THREAD

**Issue by zaped212** [peterbuga/HASS-sonoff-ewelink#197]
Recently enabled this in my HA instances, and have around 8 S31 units spread throughout the house.
Would be incredibly handy to be able to assign individual devices to areas.

**Comment by peterbuga** [comment]
@zaped212 with all due respect i have no idea what this means :| 
could you at least give an example of another *area-assignable entities* that you're using inside HA? (a screenshot would help too i think)

**Comment by zaped212** [comment]
@peterbuga 
No worries, I may not be using the correct HA terminology.
Maybe this is a hass.io thing as well and not a true HA thing, im not quite sure.

In Hass.io under configuration -> areas
This allows you to create new Areas in your house
![image](https://user-images.githubusercontent.com/589098/71589068-34cfc680-2ae9-11ea-8bd7-15d0259e8c4e.png)

Then in the "integrations page" you can go to each integration and go into the settings for each item and specify what room that item is in:
This is the integrations page for my Phillips hues
![image](https://user-images.githubusercontent.com/589098/71589357-32ba3780-2aea-11ea-9712-2d2724c59b8c.png)
Note that each light is assigned to the "Master Bedroom"

Then on the overview page it groups all of the items ( switches, lights, sensors ) based on the room that its in:
![image](https://user-images.githubusercontent.com/589098/71589295-03a3c600-2aea-11ea-861b-9b3635eb2baa.png)

As for other examples:
I can do this with: Google Homes, Phillips Hues, Even my Ecobee thermostat.

**Comment by peterbuga** [comment]
have you tried this https://www.home-assistant.io/docs/configuration/devices/#grouping-devices ? sounds a lot like what you're requesting :/

**Comment by zaped212** [comment]
It looks like areas might be a new feature ( released early 2019 mayb )
Also seems like it is also only supported for "integrations"

Here is a link to a discussion on it:
https://community.home-assistant.io/t/confused-on-how-to-configure-areas/98499/42

For my purposes I think groups would be sufficient, and seems like it was recommended on that discussion as well.
