### ISSUE TITLE
Problem with region (solved) - Also posted some json info you might like - Sonoff 4CH PRO R2

### ISSUE THREAD

**Issue by 2016for** [peterbuga/HASS-sonoff-ewelink#2]
Here's the error:

```
Traceback (most recent call last):
  File "sonoff-debug.py", line 57, in <module>
    headers.update({'Authorization' : 'Bearer ' + user_details['at']})
KeyError: 'at'

```

Would appreciate your help. Thanks.

**Comment by 2016for** [comment]
Okay Solved: changed my region to 'us' instead of 'eu'

I have the devices.json file

Just trying to figure out the sensitive data. 
It would be easier if you tell me what data you're looking for and I can send you that?

**Comment by 2016for** [comment]
I think this is what you're looking for. Instead of "switch" it was this:

```
"switches": [
        {
          "outlet": 0, 
          "switch": "off"
        }, 
        {
          "outlet": 1, 
          "switch": "off"
        }, 
        {
          "outlet": 2, 
          "switch": "off"
        }, 
        {
          "outlet": 3, 
          "switch": "keep"
        }
      ]
    }, 
    "productModel": "4CH Pro", 
```

**Comment by 2016for** [comment]
Seems like adding support for more devices shouldn't be difficult. :)

**Comment by peterbuga** [comment]
I just realised I didn't commit the last version of the script >.< (that's what I get for coding at midnight). 
Also I completely forgot about the regions redirection, my bad!

I will also add auto-obfuscation of sensitive data 👍 thanks for sharing!

**Comment by 2016for** [comment]
You sir are Amazing! 
Appreciate the contribution!

**Comment by peterbuga** [comment]
Out of curiosity, how do you have the Sonoff 4CH Pro setup? According to [this page](https://www.itead.cc/wiki/Sonoff_4CH_Pro) there are 3 states: 

> Users can switch among 3 modes: self-locking mode, inching mode and interlock mode. In self-locking mode, users can turn on/off the 4 connected devices independently. In inching mode, users can turn on connected devices for 0.25-4s(Sonoff 4CH Pro) or 1-16s (Sonoff 4CH Pro R2). In interlock mode, users can turn on 1 device every time, and turn off other devices at the same time.

**Comment by 2016for** [comment]
based on description: Self-locking mode ie all 4 devices turn on/off
independently

**Comment by peterbuga** [comment]
Just pushed the first version for devices with multi switches based on the above output. It's quite although not hard to do it, some problems might show to do being unable to do even 1 single test 😆

**Comment by peterbuga** [comment]
solved.
