### ISSUE TITLE
HA Docker

### ISSUE THREAD

**Issue by max-rh** [peterbuga/HASS-sonoff-ewelink#20]
Hello there,
Thanks for this integration, I've been waiting for this for a long time;
Can you please advice on how to do this integration if you have HA running in a docker container ?

Thanks

**Comment by peterbuga** [comment]
Hi @max-rh, 
Unfortunately I'm not quite familiar on how exactly how HA works with the docker containers nor the problems that might rise with it. It's safe to assume this install it's just like any other custom component install and I'm highly confident you might find some similar questions/fixes on https://community.home-assistant.io/
