### ISSUE TITLE
Add To HACS

### ISSUE THREAD

**Issue by codeclinic** [peterbuga/HASS-sonoff-ewelink#204]
Is there any chance that you could add this component to HACS? That way it'd get more exposure plus installation and updates would be really easy. Not to mention that we would get a notification every time a new update is released for this.

Thanks.

**Comment by peterbuga** [comment]
hi @codeclinic 
already answered to this request more than a few times. i'm not looking for exposure, this a simple hobby project that i wanted to share (worked for me so why not for others too). when it stops working ...there are always alternatives
i might consider it if the component matures to a stable version _sometime_ in the not-so-near future

hope you understand

**Comment by codeclinic** [comment]
Sure. It'd make it easier for users to install and update. But, it's your project to do with as you see fit.

Thanks for working on it.
