### ISSUE TITLE
HA web interface not accessible with this component added to config files

### ISSUE THREAD

**Issue by codeclinic** [peterbuga/HASS-sonoff-ewelink#205]
With the credentials / config for the component added to my HA configuration.yaml HA fails to startup properly and I cannot access the web interface. I tried running the debug script but this just results in a devices.json file with the following content:

{
  "error": 400,
  "msg": "params incomplete"
}

Any ideas on what I should do now. HA works fine with the config entry commented out.

**Comment by codeclinic** [comment]
After running the script manually it became evident that some of the dependencies were missing. These included:

websocket
voluptuous

However, I'm still not able to get HA running to the point of getting in to the web interface. The logs don't show anything special even with the debugging option enabled  and with the HA logging level set to Debug.

The farthest the logs show HA reaching is homeassistant.components.recorder Connected to recorder database.

**Comment by codeclinic** [comment]
It would probably help to mention the dependencies in the readme or even better to create a requirements file.

**Comment by peterbuga** [comment]
> It would probably help to mention the dependencies in the readme

no need, they are installed automatically (or at least they should)

> even better to create a requirements file

according to HA documentation custom components don't need it so i don't bother with it

**Comment by codeclinic** [comment]
> ps: i find it unbelievable hard to believe you had to install voluptuous manually as this one is one of HA's extremely used package

I must be a idiot or a liar then.
