### ISSUE TITLE
Error 400 ,  "msg": "params incomplete"

### ISSUE THREAD

**Issue by aladin2000** [peterbuga/HASS-sonoff-ewelink#207]
Using 105.0B2 for HASS andlast version of custom...
 
It  Used to work once and them I got that error message for debug
 
Error during setup of component sonoff 

python3 -d sonoff-debug.py -u 'MyUser@MydomainMail' -p 'My Password'
{
  "error": 400,
  "msg": "params incomplete"
}

do not know how to fix it   - Any Clue ?

**Comment by peterbuga** [comment]
what code version are you using?

**Comment by greyfenrir** [comment]
have the same issue. Looks similar to [this](https://github.com/gbro115/homebridge-ewelink/issues/56).
I'm newbie here so step by step:
1. hass 0.103.0 installed to RPI 3. some devices works (e.g. tuya)
2. sonoff directory from HASS-sonoff-ewelink (today taken from master) placed into <conf_dir>/custom_components, no error in logs (after websocket-client addition)
3. sonoff config with login(email)/pass/debug only. Also I tried eu/us regions. 
4. absolutely nothing on webUI (overview/debug/etc).
5. sonoff-debug returns the same json as in TS case.

**Comment by greyfenrir** [comment]
additionally: described situation was three days ago (Feb 12), today all is ok.

**Comment by pawelbura** [comment]
I have exactly the same error output with sonoff-debug.py script
my pull request is fixing this (some parameters were missing)
