### ISSUE TITLE
Sonoff LED Controller

### ISSUE THREAD

**Issue by nickrout** [peterbuga/HASS-sonoff-ewelink#21]
The Sonoff LED device has been discontinued, but it consisted of a Sonoff Basic form factor box attached to a string of white LEDs. I can't find it on their website any more. Anyway, here is the output of sonoff-debug. 

http://paste.ubuntu.com/p/34s5KKmMk3/

**Comment by peterbuga** [comment]
Hi, I didn't even knew this one exists. 
Can you please give me a few more details how this works (what are the available settings for this device in eWeLink app) do they match the ones in the bottom page video from here https://www.itead.cc/sonoff-led.html ? 

It's unclear to me if the LEDs are only warm-cold + brightness setting or you can also set any color to them too.

Needless to say I'm willing to invest time to add this device if you can also spare some to do some debugging, pretty sure I cannot develop this blindly without being able to do any kind of tests on my side :sweat_smile:

**Comment by nickrout** [comment]
That is the very device, I am not sure why I couldn't find it. Well done.

It is warm/cool white light, so two channels, each dimmable. 

Happy to work with you.

**Comment by peterbuga** [comment]
Hi @nickrout hope you had some good holiday time :)

I'm slowly resuming the work on this component and while re-reading this issue turns out I need a few more `sonoff-debug.py` outputs from you in order for me to understand how this device actually works.
I need you to set the lights at various settings and run the debug script (unfortunately I know this is going to be a bit tedious task because the script is going to log you out of the mobile app every time, unless you create a 2nd account and share the device there). Do something like this:
- warm + 1% (or lowest value that can be set) brightness
- warm + 50% brightness
- cool + 100% brightness

Label the outputs accordingly and hopefully this should be enough for me to get it up'n'running.

**Comment by peterbuga** [comment]
@jeffreysweeris your problem looks similar to this opened issue https://github.com/peterbuga/HASS-sonoff-ewelink/issues/37 please follow that thread and _help me to help you_ to provide the device debug data. Even though the device mentioned above might look/act like yours, the more data I have easier/better for me to implement it.

Without this information I have no idea how the device works => I cannot do magic 😝

**Comment by nickrout** [comment]
@peterbuga thanks it might take me a day or so to get that done, but I will do my best.

For ages I have just been turning it on and off with the wall switch - and didn't even realise it has actually fallen off my wifi. Likely because I changed my AP a while ago. It'll require a bit of work to get it back to fully functional, then I'll get you the nfo.

**Comment by peterbuga** [comment]
@nickrout take your time, whenever you can 😉 thanks for the help!

**Comment by peterbuga** [comment]
hi @nickrout do you still use this device? i've been implementing the Sonoff B1 device which looks terrible similar with this one in the backend, it's still work in progress with a few bugs to be fixed but i would appreciate if you could take the time to give a try to the `sonoff-bulb` branch and let me know if it works for you too.

thanks!

**Comment by nickrout** [comment]
I am using simply as a wall switched light. I changed my AP and it still tries to connect to the old one. I tried to  reconfigure to the new AP but something went wrong and I ran out of time.

Am taking time off over Easter and will try again!

**Comment by peterbuga** [comment]
No worries! I was just curious if you're still interested in this component and in the same time a confirmation that this actually works too now. 
Take your time and if you get it to work please let me know, thanks!

**Comment by peterbuga** [comment]
i just realized this has the same control format as Sonoff B1 https://github.com/peterbuga/HASS-sonoff-ewelink/issues/34 

closing due to the fact it's a high chance it works already + the lack of new information
