### ISSUE TITLE
Sonoff POW (first generation) voltage and current values

### ISSUE THREAD

**Issue by KixMan28** [peterbuga/HASS-sonoff-ewelink#213]
I have installed your software and it works fine. It recognizes all my Sonoff devices (Basic, S20, POW and Touch). My questions is: can I extract somehow the current and voltage values (as the power value) from my Sonoff POW (first generation, firmware 2.6.1)?

**Comment by peterbuga** [comment]
they should be listed under **attributes**
i have a POW R2 and i have it like this 
```device_id: 1000xxxxxxx
power: 0.00
current: 0.00
voltage: 224.43
rssi: -64
friendly_name: speakers
```

on top of the fact the component created separate entities for power/current/voltage (in my case)

```
sensor.sonoff_1000xxxxxx_current | 0.00 | unit_of_measurement: A friendly_name: speakers current icon: mdi:current-ac
sensor.sonoff_1000xxxxxx_power | 0.00 | unit_of_measurement: W friendly_name: speakers power icon: mdi:flash-outline
sensor.sonoff_1000xxxxxx_voltage | 222.32 | unit_of_measurement: V friendly_name: speakers voltage icon: mdi:power-plug
```

**Comment by KixMan28** [comment]
As I mentioned in my initial post I have first generation Sonoff POW's and if I check the entity attributes I see only this:
`device_id: 10000bb678
power: '17'
rssi: -67
friendly_name: NAS`

How can I access the voltage and current?

**Comment by peterbuga** [comment]
according to this older issue https://github.com/peterbuga/HASS-sonoff-ewelink/issues/14 and the provided dump, the sonoff POW (compared to POW R2) exposes **ONLY** the **power** value. in other words, if you cannot see them in the eWeLink app you cannot get them in HA (you can also check the differences in POW vs POW R2 in sonoff features description pages)

please confirm and close this issue.

**Comment by KixMan28** [comment]
OK. Thank you for your reply. I am closing the issue.
