### ISSUE TITLE
Sonoff BASIC component hangs HA start

### ISSUE THREAD

**Issue by ttecles** [peterbuga/HASS-sonoff-ewelink#215]
Hi, 

I downloaded the code and added to the folder but when I start the HA, it hangs on the following line:

```
de febr. 26 21:14:55 raspberrypi hass[3845]: 2020-02-26 21:14:55 INFO (MainThread) [homeassistant.setup] Setting up cloud
de febr. 26 21:14:55 raspberrypi hass[3845]: 2020-02-26 21:14:55 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 3.8 seconds.
de febr. 26 21:14:55 raspberrypi hass[3845]: 2020-02-26 21:14:55 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.1 seconds.
```

**Comment by labachev** [comment]
Same here, 
After update to HA Core 0.106 it says it can't find sonoff component.

**Comment by peterbuga** [comment]
@labachev did it worked before? simply update => not working anymore?
trying to pinpoint if it's an install problem or braking change problem

**Comment by labachev** [comment]
@peterbuga : After update to 0.106.1 it cannot load the component.
Error in log is:
[homeassistant.components.homeassistant] Component error: sonoff - Integration 'sonoff' not found.

**Comment by Dergonic** [comment]
Same for me. Was ok when running 0.105.x bit not more while running 0.106.4.

Logs says :

> Log Details (ERROR)
> Logger: homeassistant.setup
> First occured: 11:00:13 AM (1 occurences)
> Last logged: 11:00:13 AM
> 
> Setup failed for sonoff: Integration not found.

Files are still in custom_component folder and I check the whole config and it looks ok.
I'm available if anyone need more info ;)

**Comment by browetd** [comment]
Probably the same issue on my side... I tried to transfer HA from one Raspberry PI4 to another one...  I backup all the HA files from the old and restored everything on the new (I am running in a venv python 3.7.3 on the old one and 3.8.2 on the new one)...  HA 0.106 on both ... Sonoff is running on the old one but not in the new environment... No error message, just HA stuck during startup (0% cpu used)... Maybe a different version of Websocket or a Python issue due to a different version in the new environment or ... ?

**Comment by browetd** [comment]
I made some additional tests... I restored my initial test environment: HA 0.106.5 running in a venv with python 3.8.2 on a raspberry pi4B (2GB).

### I added the file manifest.json in custom_components/sonoff with the following content:

{
  "domain": "sonoff",
  "name": "Sonoff",
  "documentation": "https://github.com/peterbuga/HASS-sonoff-ewelink",
  "requirements": ["websocket-client==0.54.0"],
  "dependencies": [],
  "codeowners": ["@peterbuga"]
}

### IT IS WORKING !!! SONOFF is loading... Check is this is not fixing your issue as well

**Comment by Dergonic** [comment]
Looks like I solved mine, but not sure how. Here is what I did (as far as I remember):

1- I applied @browetd solution and restated through Webinterface (I assume it only restarted the docker container)
2- As soon as it was still not working, I went deaper and read @browetd was speaking of Python3 while python was only 2.7.17 on my Hassio host. I Installed Python 3.7.5. 
3- (I updated my SSL certificate which was expired - I don't know if it can be any important)
4- I restarted the whole HOST (sudo reboot on the docker host)

Then it is ok ! 
I have no idea which point solved the issue or if a combination of several. If any dev/pro need any other information, I'll be pleased to help.

**Comment by KixMan28** [comment]
@browetd  Thank you for the tip. it worked for me too. I just added the manifest.json file with the content you mentioned in the location you mentioned and restarted my HA. All my Sonoff appeared immediately.

**Comment by browetd** [comment]
I still don't understand why the same configuration (one created and upgraded for about a year) and the other one created this week-end from scratch have different behaviour with the same files (I did a full backup of the "upgraded" home assistant directory (/home/homeassistant) and restored it in the new environment before starting Home Assistant with the json file as explained)...  Nevertheless, happy that this fix is helping...  I am now in full prod with the new environment !

**Comment by peterbuga** [comment]
@browetd i assumed the `manifest` file might have something to do with it, although last time i check HA listed in their blog that custom components don't require this file `¯\_(ツ)_/¯`

**Comment by browetd** [comment]
@peterbuga  You are 100% correct,  I checked this morning the documentation and it is still mentioned " It is required to add such a file, except for custom components."... Soooo.... ???  but for me it fixed the issue... Maybe if confirmed, the documentation should be updated if the statement about manifest.json file requirement is not true anymore...

**Comment by ttecles** [comment]
solved for me too! Great job @browetd

**Comment by KixMan28** [comment]
Now this is strange. Yesterday I added the manifest.json file to my sonoff folder, because my Sonoff devices were not showing up in HA. Today my devices disappeared  again. This time I removed the manifest.json file from the sonoff directory and the devices appeared again in HA.

**Comment by x-Felix** [comment]
I disabled sonoff component in configuration.yaml today before upgrading Hassio 3.12 to 3.13. 
After successfully upgraded to Hassio 3.13, I tried to enable sonoff components but failed with HA hangs. 
The last line of the 'ha core log' output `is 2020-04-17 12:24:26 INFO (MainThread) [homeassistant.setup] Setting up sonoff`
Cannot run ha core restart at this stage, just with error. Have to do a power cycle after disabled sonoff component in configuration.yaml. Then it returns normal. 
Tried to delete the __pycache__ file under sonoff custom_component folder, also tried put manifest.json file there, no use. All attempts with sonoff enabled in configuration.yaml hang HA start.

**Comment by peterbuga** [comment]
@x-Felix 
>No idea this component may have dependency on Internet connectivity?

this component is STRICTLY using the internet connection, as it's simulates an ewelink app! i recommend to increase the `scan_interval` to a higher value (600-1800) if you're stuck to a limited 4G connection, this value is more like a fallback-status-update. most of the updates are done via websockets
