### ISSUE TITLE
Long time to sensor update, about 10 hours

### ISSUE THREAD

**Issue by nick2525** [peterbuga/HASS-sonoff-ewelink#217]
It is not usable, because sensor updates not every minute, but every 10 hours, sometimes every 24 hour

**Comment by peterbuga** [comment]
@nick2525 can you please give more details, what sensor what device what firmware you have, HA version and what base system!

**Comment by nick2525** [comment]
I have sensor.sonoff_voltage, sonoff pow r2, firmware 3.3.1, Home Assistant > 

arch | armv7l
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.8.0
version | 0.106.2
virtualenv | true
raspberry pi 3

**Comment by peterbuga** [comment]
have a reading here to see why it's not updating properly anymore https://github.com/peterbuga/HASS-sonoff-ewelink/issues/128 and here https://github.com/peterbuga/HASS-sonoff-ewelink/issues/128#issuecomment-553023164
