### ISSUE TITLE
ewelink on Android and in HA at the same time

### ISSUE THREAD

**Issue by Roberto6969** [peterbuga/HASS-sonoff-ewelink#218]
Hello, thank you for your great work!
Actually, this is probably not an issue or error. I would like to use ewelink, logged in on Android app, and in Home Assistant also.

Now, after use on Android, i have to restart Home Assistant to make it work. But after that, i have to log again in Android app to use it (due to message "session expired"). Everytime when i use Android app, i loose connection in Home Assistant.

Do you have any workaround for this problem? Could be one sonoff device linked to two accounts - if this is solution?

Thank you!

**Comment by peterbuga** [comment]
read the documentation, use a 2nd account and share the devices
