### ISSUE TITLE
Add HACS (Community Store) Support

### ISSUE THREAD

**Issue by qJake** [peterbuga/HASS-sonoff-ewelink#222]
Please add support for [HACS (Home Assistant Community Store)](https://hacs.xyz).

It would allow anyone who uses HACS to find your integration when searching "Sonoff", and also install your integration with one click.

A guide on how to make your repository HACS-compatible can be found here:

https://hacs.xyz/docs/publish/integration

I don't personally know what's involved in this, but I am hoping you can tweak a few things and get this to work, so that users don't have to install this component manually and you can push out updates much quicker!

Thanks!

**Comment by peterbuga** [comment]
hi @qJake
it has been requested before but I’m not planning to do it (anytime soon)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
