### ISSUE TITLE
error with custom_components/sonoff

### ISSUE THREAD

**Issue by guyyar89** [peterbuga/HASS-sonoff-ewelink#223]
i have version 0.104.3

home assistant bug
![image](https://user-images.githubusercontent.com/43018733/77232639-f1966880-6baa-11ea-946f-3d9fdca67a53.png)

![image](https://user-images.githubusercontent.com/43018733/77232680-34584080-6bab-11ea-9865-0705d14ac31c.png)

how to fix it?

**Comment by peterbuga** [comment]
@guyyar89 doesn’t look like my code 😅
can you drop a link from where you’ve got it? i’m curious 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by guyyar89** [comment]
its install from hacs
where is the code?

**Comment by peterbuga** [comment]
wrong project, here's the one that you're looking for https://github.com/AlexxIT/SonoffLAN (this dude did some pretty good job) follow up there (+next time read better the description from HACS, pretty sure there's some reference there)
