### ISSUE TITLE
Has anyone experienced HA getting stuck in the past two days?

### ISSUE THREAD

**Issue by schachar** [peterbuga/HASS-sonoff-ewelink#224]
In the past 2-3 days HA gets compleatly stuck and doing strace I find out its stuck on read from a socket connected to 3.0.32.5 which is as-api.coolkit.cc one of sonoff endpoint

anyone experiencing the same?

**Comment by viveiroscordeiro** [comment]
I'm a newbie but I notice some sever problems on home assistant, and had this log information: 

`20-03-31 01:49:56 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 01:49:56 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config` 

The fact is that removing the sonoff add-on solved the problem. I don't know if it's related...

**Comment by peterbuga** [comment]
is your connection using some custom DNS? it does happen sometimes for servers to not respond for various reasons also

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
