### ISSUE TITLE
SONOFF Team have emailed me about your integration

### ISSUE THREAD

**Issue by niccolobusato** [peterbuga/HASS-sonoff-ewelink#225]
sonoff have emailed me saying this:

Hello, Author

My name is Daniel from SONOFF marketing, appreciating your project on Github: https://github.com/niccolobusato/Main-Home-AssistantConfig

It is a good project,  SONOFF pays more attention for the development of the open source community and hope to provide you with better services.

Recently, I received a notification from eWeLink that your project need to be optimized if users would like to continue use it.

I checked your project and found that there are some areas that can be optimized:

1. Since the APPID and App Secret used in your project are about to expire (calling the signature key of the HTTP request), we have specially assigned you a new APPID and App Secret.

APPID: xxx

App Secret: xxxxx

It is unique and only provided for your use. I hope you can complete the replacement as soon as possible to avoid subsequent failures to call the eWeLink interface. 

2. We checked the request logs from third-party clients on the server and found a large number of unreasonable HTTP requests. The reason is that some open source projects only need to obtain the status of a single device, but call "Get All Device List: /api/user/device" interface, which will cause a lot of congestion in eWeLink services.

So we recommend that you and other open source project authors use WebSocket to monitor the status of the device in real time.

Related documentation link: https://coolkit-technologies.github.io/apiDocs/#/en/APICenter?id=websocket-inquire-device-status

If you are not familiar with WebSocket, we also provide an HTTP interface for querying the status of a single device:

Related documentation link: https://coolkit-technologies.github.io/apiDocs/#/en/APICenter?id=http-check-device-status

Note:

1. When the status of the eWeLink device changes, it will report a message to the server of the eWeLink platform (instruction type: update). As long as your project uses WebSocket to establish a long connection, you can receive this information, so all third-party customers are recommended When the client is turned on, after connecting to the external network, it actively establishes a long-term connection to continuously monitor the device status of eWeLink or send query commands to obtain the status of a single device, instead of requesting the "Get Device List" HTTP interface regularly, which is reasonable and standardized.

2. We will limit the frequency with which the same IP requests the same interface for a period of time. If there are too many requests, our server will temporarily disable this IP. May cause confusion for users using this plugin,So please try to set the interval between requests for the same interface to more than 30 seconds.There are no strict restrictions on websocket, so this is recommended.

I hope this can help you, thank you for your support!

Best wishes from SONOFF

can you do anything? thanks, have a nice day!

**Comment by peterbuga** [comment]
@niccolobusato thanks for the heads up, appreciate 🙌!
this looks like a similar request from here https://github.com/peterbuga/HASS-sonoff-ewelink/issues/209 (i think)
interesting though, they gave you an APPID/AppSecret so enjoy while you still can ;) 

i kept planning to do serious updates to the component but if the general/common APPID will be canceled this project will be dead soon :/

**Comment by niccolobusato** [comment]
should i just replace  APPID/AppSecret  in my _init_.py?

**Comment by peterbuga** [comment]
@niccolobusato in theory yes, never had alternative credentials to test with and if I remember right the appsecret on my side was somehow decoded at some point, just try it see if works
