### ISSUE TITLE
Don't show "Unavailable" units in Home Assistant

### ISSUE THREAD

**Issue by oskarscholander** [peterbuga/HASS-sonoff-ewelink#227]
Hi!

Some of my Sonoff units are flashed with Tasmota and shows up as "Unavailable" in Home Assistant with this custom component!

Is it possible to now show those from this component?

/ Oskar

**Comment by peterbuga** [comment]
@oskarscholander you should remove them from eWeLink app, that's where the information is pulled from. by any means, i **cannot** detect any of the devices that had been flashed with tasmota
let me know if this works!
