### ISSUE TITLE
Can't add to HACS as repo

### ISSUE THREAD

**Issue by garybsimon** [peterbuga/HASS-sonoff-ewelink#228]
Hi @peterbuga!

I have tried to add your custom repo to HACS as it worked in the past without any issues.
Now I get the attached error, that show it's not compliance with the latest version.
Have you any idea how to fix this issue?

Thanks a lot. Regards. 

![image](https://user-images.githubusercontent.com/1783851/78295853-0c62c880-752d-11ea-8b0b-e01a201510d7.png)

**Comment by peterbuga** [comment]
@garybsimon pretty sure this is not my repo. 
this component doesn’t (and probably never will) have HACS support 😞 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by garybsimon** [comment]
@peterbuga such an interresting fact. I have used with the last HACS version without any problem.
But never mind, I'll use it as it is. 👍

**Comment by garybsimon** [comment]
@peterbuga I have manually add the files to my custom_component folder, edited the configuration.yaml and restarted the HA instance, but the Sonoff component is not visible. I doesn't even get an error message. Can you please advise where to start to debug? sonoff-debug?

**Comment by peterbuga** [comment]
without any errors i don’t even know where to start. you have to hive something more than that...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
