### ISSUE TITLE
Component error: sonoff - No module named 'Crypto'

### ISSUE THREAD

**Issue by mattlward** [peterbuga/HASS-sonoff-ewelink#229]
I am running home assistant 0.107.7 and  v1.10.3 of your HACS addon and ran the config check to prep to go to 0.108.0 and I have the following error in the output logs.

INFO:homeassistant.util.package:Attempting install of HAP-python==2.8.1
Failed config
  General Errors: 
    - Component error: sonoff - No module named 'Crypto'

Can you provide any insight to this or is there a fix needed for 0.108.0?

**Comment by peterbuga** [comment]
unfortunately this is not my plugin you’re reffering to. mine doesn’t (and for obvious reasons probably never will) have HACS support.
good luck 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
