### ISSUE TITLE
Could you add file manifest.json

### ISSUE THREAD

**Issue by jgrycz** [peterbuga/HASS-sonoff-ewelink#230]
Hi,

I use your component and it works really nice, but when this component was added to my HA project, CI started failing.

In my CI github does simple config check:
_hass -c . --script check_config_

When github ran it, I had below error:
_Run hass -c . --script check_config
  hass -c . --script check_config
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.6/x64
INFO:homeassistant.util.package:Attempting install of colorlog==4.1.0
Testing configuration at /home/runner/work/home/home/.
INFO:homeassistant.util.package:Attempting install of bt_proximity==0.2
INFO:homeassistant.util.package:Attempting install of pybluez==0.22
....
INFO:homeassistant.util.package:Attempting install of mutagen==1.43.0
INFO:homeassistant.util.package:Attempting install of gTTS-token==1.1.3
Failed config
  General Errors: 
    **- Component error: sonoff - Integration 'sonoff' not found.**_

So clearly HA couldn't find sonoff integration despite of having it in repo. 

Solution:
This problem has been solved once I've added manifest.json file which looks like following file: https://github.com/jgrycz/home/blob/master/custom_components/sonoff/manifest.json

Failed build:
https://github.com/jgrycz/home/runs/555180534?check_suite_focus=true

Passed build, with manifest.json:
https://github.com/jgrycz/home/runs/573993740?check_suite_focus=true

**Comment by peterbuga** [comment]
hi @jgrycz 

there's been reported now and then this `manifest.json` (there's even a PR for it https://github.com/peterbuga/HASS-sonoff-ewelink/pull/111 ) but HA docs says it's not needed for custom components and it has been reported that it works for some people just fine and for others (like you) not so much for some reason `¯\_(ツ)_/¯`

it has also been reported that iTead works on blocking this component soon (and others based on its logic), so it's just a matter of time till it's gonna drop dead. it was fun while it lasted, brought some life in sonoff devices for a limited time 😄
