### ISSUE TITLE
May cause HA web not responding

### ISSUE THREAD

**Issue by x-Felix** [peterbuga/HASS-sonoff-ewelink#231]
I am new to HA. Spent some time during this Easter to get everything on HA.
This eWeLink component is exactly what I need. Tested and worked. However after leaving it sometime maybe hours, HA web is no longer accessible, not responding timeout. I can still access SSH to restart the service to bring it back. But after another hour, HA web dead again. 
I disabled sonoff component in configuration.yaml then no more issue with web access.

Hassio 3.12, Supervisor 217
Hardware: raspberry pi 3B+

Please help. I saw a notification or log in HA mentioned sonoff is a custom component which may cause stability issue. Not sure how to get it work smoothly. Thanks.

**Comment by peterbuga** [comment]
@x-Felix i need more details maybe some logs without them there's not much i can do. if you have a lot of devices maybe increasing the `scan_interval` value (like 900, feel free to experiment) to bigger value might help.

> I saw a notification or log in HA mentioned sonoff is a custom component which may cause stability issue. Not sure how to get it work smoothly.

this is a normal message from custom components

**Comment by x-Felix** [comment]
Thanks, @peterbuga .
I increased scan_interval from 180 to 600. And enabled debug logging. Hope it will capture some useful information next time web hangs.

**Comment by x-Felix** [comment]
I cannot reproduce the issue anymore after increase the scan interval to 600 and more. 
Close this issue for now. Thanks.
