### ISSUE TITLE
Important Notification From SONOFF

### ISSUE THREAD

**Issue by Daniel-zhan-itead** [peterbuga/HASS-sonoff-ewelink#236]
As eWeLink will stop provide the support and maintance of current APPID & APP secret on Aug 31th 2020. 

That means that this project may work improperly.

eWeLink will offer a special APPID and APP secret for this project.

@peterbuga  Please contact me via the mail 

To: daniel.zhan@itead.cc
and cc: jiale.liu@coolkit.cn

Daniel

**Comment by PMaxx-Gaming** [comment]
@peterbuga, any idea if this is legit or not? I got the same notification.

**Comment by krasatos** [comment]
> @peterbuga, any idea if this is legit or not? I got the same notification.

Well if it is, kudos to ITEAD for reaching out to the community.

**Comment by peterbuga** [comment]
@PMaxx-Gaming 
> @peterbuga, any idea if this is legit or not? I got the same notification.

seems legit enough for me 🤷‍♂️ 

---

@Daniel-zhan-itead email sent, thanks for taking the time & reaching out. looking forward for your reply!
