### ISSUE TITLE
Compatibility Issues with HA 0.115

### ISSUE THREAD

**Issue by MrGravgaard** [peterbuga/HASS-sonoff-ewelink#259]
When using your component on 0.115, the init fails because it is missing a requirement. 

"ERROR (MainThread) [homeassistant.setup] Setup failed for sonoff: Requirements for sonoff not found: ['uuid']."

Is it possible to fix? I'm really happy about your custom component. 

Best regards, 
Christian Gravgaard

**Comment by pepr2018** [comment]
Same problem here.

Work very well unitl now.

Thanks

**Comment by ThisBytes5** [comment]
Same here too even with 0.115.1

**Comment by victorprietotome** [comment]
Same problem with 0.115.1, downgraded to 0.114.0 and works fine.

**Comment by victorblanco** [comment]
Same problem 0.115.1

**Comment by heiblum** [comment]
Same problem with 0.115.2

**Comment by johnjoemorgan** [comment]
Following this from afar ... @peterbuga has stated he won't be working on this project moving forward.  The only way yo get this fixed is to fix it ourselves or use SonoffLAN or similar

**Comment by ThisBytes5** [comment]
> Same problem with 0.115.1, downgraded to 0.114.0 and works fine.

How do you downgrade? I need this working sooner then later as we are traveling and use it to monitor the RV temp for the dog while we are out and about.

**Comment by eriklefevre** [comment]
Downgrading back to 0.114 with a snapshot made before this update 0.115 works.

**Comment by edalcin** [comment]
Same problem with 0.115.2

**Comment by rlcobos2** [comment]
Hi, I have found this component . Works perfectly with all the sonoff products.

https://github.com/AlexxIT/SonoffLAN

**Comment by cmilanf** [comment]
Moved to https://github.com/AlexxIT/SonoffLAN, available from HACS, and my TH16 is working again.

**Comment by eriklefevre** [comment]
Thank you all. Everything working on latest version 0.115.2 and AlexxIT/SonoffLan.

**Comment by diazdeespada** [comment]
Same problem

**Comment by eriklefevre** [comment]
Hi diazdeespada, problem is solved. Read last messages!

**Comment by aladin2000** [comment]
Hi
What are thé drawback in changing solution to the other components ?  Does it impact old entities ?
What id the HowTo ?

21 sept. 2020 10:18:40 eriklefevre <notifications@github.com>:

**Comment by MrGravgaard** [comment]
I close this issue, as I moved on to AlexxIT/SonoffLAN. 
it is point and click in HACS, configuration is the same, the entries is named the same and it works. 

This product doesn't work anymore.

**Comment by ThisBytes5** [comment]
thanks for pointing out https://github.com/AlexxIT/SonoffLAN, from HACS, and everything is working again, and now my hedgehog and dog will be good!

if you're using the temperature/humidity of the TH, make sure to add the sensor creation to your config.
