### ISSUE TITLE
Temperature sensor support - TH10/TH16

### ISSUE THREAD

**Issue by hernani** [peterbuga/HASS-sonoff-ewelink#27]
Just opened a PR adding support for temperature sensors for devices that provide this innformation such as TH16.

https://github.com/peterbuga/HASS-sonoff-ewelink/pull/26

**Comment by peterbuga** [comment]
could you please send the `sonoff-debug.py` output so I can have a reference to it? I will also like to add the humidity sensor also if possible

**Comment by hernani** [comment]
Here is an example.

  {
    "__v": 0, 
    "_id": "[hidden]" 
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "brandName": "Maker", 
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "deviceStatus": "", 
    "deviceUrl": "", 
    "deviceid": "[hidden]" 
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "extra": {
      "_id": "[hidden]" 
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx", 
        "brandId": "5611402280a0e2630f7b102d", 
        "description": "WWJG000898", 
        "mac": "xx:xx:xx:xx:xx:xx", 
        "manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8", 
        "model": "PSA-BHA-GL", 
        "modelInfo": "566e54549f6c65fc6f8953c5", 
        "ui": "\u6052\u6e29\u6052\u6e7f\u6539\u88c5\u4ef6", 
        "uiid": 15
      }
    }, 
    "group": "", 
    "groups": [], 
    "ip": "[hidden]" 
    "location": "", 
    "name": "[hidden]", 
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "online": false, 
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "params": {
      "controlType": "7", 
      "currentHumidity": "unavailable", 
      "currentTemperature": "16", 
      "deviceType": "normal", 
      "fwVersion": "2.6.0", 
      "init": 1, 
      "mainSwitch": "off", 
      "rssi": -67, 
      "sensorType": "DS18B20", 
      "staMac": "xx:xx:xx:xx:xx:xx", 
      "startup": "off", 
      "switch": "off", 
      "timers": [
        {
          "at": "0 8 * * 1,2,3,4,5", 
          "coolkit_timer_type": "repeat", 
          "do": {
            "mainSwitch": "off", 
            "switch": "off"
          }, 
          "enabled": 1, 
          "mId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
          "type": "repeat"
        }
      ]
    }, 
    "productModel": "Sonoff THS", 
    "settings": {
      "alarmNotify": 1, 
      "opsHistory": 1, 
      "opsNotify": 0
    }, 
    "sharedTo": [], 
    "showBrand": true, 
    "tags": {
      "disable_timers": []
    }, 
    "type": "10", 
    "uiid": 15
  }

**Comment by peterbuga** [comment]
@hernani hi :) 
i didn't officially merge your PR yet but in theory it should merge automatically in the future when i put everything in `master` branch (i think, *do not cancel* it though!)

I've build up upon your code and I created a new branch [https://github.com/peterbuga/HASS-sonoff-ewelink/tree/sensors](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/sensors) it will mean a lot for me if you could take it for a spin and try this code (and let me know if it works properly 🤞) before I completely merge it.

ps: i am unable to properly test the code right now and as far as I don't like to say this, I blindly coded this without running it even once 😞. returning any errors will greatly help me to move forward faster

**Comment by alesoft73** [comment]
I have use now, and i see humidy ant temperature on YH16.
Work perfect.

**Comment by peterbuga** [comment]
@alesoft73 thanks for testing it out!
does the switch eventually changes its state in HA? is there like a delay or it's not working at all? 

another person reported a problem regarding the on/off state changes and I pushed a fix (as of time of writing) ~1h ago. 
can you please make sure you have the latest version of the files from `sensors` branch! 

thanks again for reporting back 👍 !

**Comment by alesoft73** [comment]
Ok, now on/off state is ok.
Many thanks!

**Comment by peterbuga** [comment]
@alesoft73 Awesome 🙌 ! 
I can finally close this issue one, feel free to report any other problems.

Thanks!
