### ISSUE TITLE
Is this compatible with  latest  release Home Assistant 2020.12? I have issue.

### ISSUE THREAD

**Issue by montyha66** [peterbuga/HASS-sonoff-ewelink#275]
I Have following issue with  latest release 2020.12
My issue is described here, but the  remediation  there did not helped at all :-( 
https://github.com/peterbuga/HASS-sonoff-ewelink/issues/261#issuecomment-744342379

**Comment by joelr** [comment]
in init.py 

remove uuid from line ~26
so it's something like:
REQUIREMENTS        = ['websocket-client==0.54.0']

remove import uuid from line ~121

then change line 134 to anything like (has to be a valid uuid, eg):
self._imei          = str('12345278-1234-abcd-abcd-123456789011')

**Comment by davidwang2000** [comment]
Same here. it seems not working on 2020.12.

**Comment by davidwang2000** [comment]
It works after upgrading to 2020.12.1.

**Comment by montyha66** [comment]
I can confirm. Same here. It works after upgrading to 2020.12.1.
