### ISSUE TITLE
Feature request: Set the mode to lan/auto/cloud for single device

### ISSUE THREAD

**Issue by mdima** [peterbuga/HASS-sonoff-ewelink#291]
Hello,
   it would be interesting to set the mode for any specific device. 
For example I would set my POW-R2 devices to local, while the temperature devices (which work only in cloud mode) I would leave auto or cloud. 

Thanks!
Michele

**Comment by peterbuga** [comment]
@mdima try/switch to https://github.com/AlexxIT/SonoffLAN
