### ISSUE TITLE
Discard wss check on macOS installs

### ISSUE THREAD

**Issue by peterbuga** [peterbuga/HASS-sonoff-ewelink#30]
HA installation on macOS tries to validate the wss connection and breaks the flow.

https://community.home-assistant.io/t/sonoff-ewelink-switch-component-for-original-firmware/81369/88?u=peterbuga

**Comment by peterbuga** [comment]
can be fixed like this:

https://community.home-assistant.io/t/sonoff-ewelink-switch-component-for-original-firmware/81369/157

https://timonweb.com/tutorials/fixing-certificate_verify_failed-error-when-trying-requests_html-out-on-mac/

**Comment by edmarts** [comment]
Worked greate! Thanks!

**Comment by Saars1337** [comment]
Is there a fix for Windows? I'm really struggling with this

**Comment by peterbuga** [comment]
@Saars1337 do yourself a favor and install a slimmed down version of linux in a VM with minimal resources and put HA there, you'll have a better life like this 👍! 

i will **never** test or support any windows related issues.
