### ISSUE TITLE
Make switchs show as lights in home assistant?

### ISSUE THREAD

**Issue by ericmiller777** [peterbuga/HASS-sonoff-ewelink#32]
Is there a simple way to do this?

**Comment by peterbuga** [comment]
@ericmiller777 You can easily use the built in customization options and change the icon if this is what you're looking for. If not, please provide more details.

**Comment by peterbuga** [comment]
@2016for excellent fix! if this is what @ericmiller777 was looking for, i wasn't aware of this option.

pretty sure both answers cover the original question but i'm waiting for a reply to properly close it

**Comment by peterbuga** [comment]
you can easily find the sonoff devices in the Developer Tools section of HA, if they show up in frontend they'll be there 100%. unfortunately this is not an issue and https://community.home-assistant.io/ has already threads answering this problem and alike 😉 

for any new feature requests and/or bugs feel free to open another issue.
