### ISSUE TITLE
"Error doing job: Task exception was never retrieved" issue under hass.io

### ISSUE THREAD

**Issue by DenielTorres** [peterbuga/HASS-sonoff-ewelink#35]
Hi there! 
Thanks so much for working on this Sonoff addition to home-assistant! 
I just implemented your solution on my hass.io running on a RaspberryPi, with 1 Sonoff POW R2, and I'm getting the following error message practically every minute since I've restarted HA. 
`Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 232, in async_update_ha_state
    state = self.state
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 426, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/switch/sonoff.py", line 48, in is_on
    self._state = self.get_state()
  File "/config/custom_components/sonoff.py", line 414, in get_state
    return device['params']['switch'] == 'on' if device else False
KeyError: 'switch'`

Would you mind letting me know what could cause this, and potentially how to solve? If this is something that has been answered before apologies, but I couldn't find any answers.
Thanks in advance!
Cheers,
Daniel

**Comment by peterbuga** [comment]
Hi @DenielTorres thanks for reaching out 👍 !

By any change do you have any other Sonoff device in your account? like a sonoff light (Sonoff B1 for example). 

Another person personally reported to me that Sonoff POW R2 is working on his side, but just to be sure follow the steps from here https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug and send me the output, it'll definitely work in the end ;)

**Comment by DenielTorres** [comment]
Hi @peterbuga! Thanks very much for the quick response! Unfortunately, I'm getting the following error when trying to tun the script: 
"Traceback (most recent call last):
  File "sonoff-debug.py", line 2, in <module>
    import argparse, sys, json, time, random, pprint, base64, requests, hmac, hashlib, re
ImportError: No module named requests"
It's the same error message with all 3 py calls you mention on the link. Is it something I'm missing? 
Thanks very much!

**Comment by peterbuga** [comment]
WOW i was not expecting that 😅 
`requests` package it's a highly common python package, a very important part of a HomeAssistant installation and comes as a surprise for someone *not* to have it (that's why i don't even check the existence of it)

i never played with hass.io, but in order to fix it (after a bit of google-ing) this command *might* help you 
`pip3 install --no-cache requests`

if not in main `sonoff.py` file find this line:
`REQUIREMENTS = ['uuid', 'websocket-client']` and change it to:
`REQUIREMENTS = ['uuid', 'websocket-client','requests']`
reboot everything and hopefully should install automatically

ps: i never talked until now with a person who has a Sonoff RF Bridge device. after you get the above problem fixed I would appreciate if you could send me the sonoff-debug.py result so that i can integrate this device also, thanks ;)

**Comment by DenielTorres** [comment]
Hi @peterbuga! thanks very much for the above info. I did everything you suggested and a little more, based on more Google search and unfortunately I can't seem to get through this issue. I'm still getting the same error message, but apparently, the `requests` package is installed successfully. Do you have any other ideas what else I could be doing, or what I'm doing wrong? :D 
Also, I would be more than happy to send over the debug file so you can integrate the bridge as well!!!!

**Comment by DenielTorres** [comment]
Okay, I was trying with some other versions of py, and now with Python3 I'm getting this error: 
`ile "sonoff-debug.py", line 22
    print 'Please read the instructions better!'
                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Please read the instructions better!')?` Does this help?

**Comment by peterbuga** [comment]
> Thanks again for the changes!!! feel like I'm just causing more troubles for you 🙈 so sorry about that! 

No problem about that 😉 debugging makes it better as long your willing to join the ride.

I pushed another quick update to `sonoff-debug.py` there was a small mismatch between this file and main component (this is not a priority file :P) I hope it works now because I'm really curious about the device types you have in your account!
Can you please even mention what types of sonoff devices you have ? I have a hunch you my might have some Sonoff B1 light or something similar, like a light maybe, that is not in the compatibility list yet. hint: if i'm right, i already have a fix for it 😎

**Comment by DenielTorres** [comment]
Sounds good, thanks! Same error with the updated `sonoff-debug.py` file, unfortunately. 

Also, I have a Sonoff Pow R2, the Sonoff RF Bridge 433Mhz and with the bridge I'm using a Wireless Door Window Detector, one of these: [Link](https://www.banggood.com/DY-MC100B-Wireless-Door-Window-Detector-Sensor-Alarm-433MHz-for-Security-Alarm-System-p-1266532.html?rmmds=myorder&cur_warehouse=CN)

**Comment by peterbuga** [comment]
I find it really hard to believe that `sonoff-debug.py` is not working with the last version :| because it shares the same code with the component, really odd!

one last test, please try `sonoff-debug.py` like this:
`python2.7 sonoff-debug.py 'email@used.com' 'password'` > devices.json
OR
`python2.7 sonoff-debug.py --email='email@used.com' --password='password'` > devices.json
OR
`python2.7 sonoff-debug.py -e 'email@used.com' -p 'password'` > devices.json
notice the use of **python2.7**  instead of simply **python** (hopefully you have this one installed 🤞) 

another thing you can do: create a 2nd eWeLink account and share devices one-by-one to it and use this account in HA customization.yaml. my bet is that Sonoff RF Bridge is breaking everything because I've never seen a dump of a device like this and I was really keen on implementing it 😁 

ps: you can run the `soonff-debug.py` script on **any** pc or mac or virtual machine as long as you have the proper packages installed. it's not mandatory to be ran inside Hassio

**Comment by DenielTorres** [comment]
Hi @peterbuga! You won't believe this but I have the dump 🗡 
 To be honest, I had to reinstall my whole python config, but I have it:
`[
  {
    "__v": 0, 
    "_id": "[hidden]" 
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "brandName": "Sonoff", 
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "deviceStatus": "", 
    "deviceUrl": "", 
    "deviceid": "[hidden]" 
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "extra": {
      "_id": "[hidden]" 
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx", 
        "brandId": "58e5f344baeb368720e25469", 
        "description": "WO1852", 
        "mac": "xx:xx:xx:xx:xx:xx", 
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8", 
        "model": "PSC-B67-GL", 
        "modelInfo": "5a2e1ae50cf772f92c342ef6", 
        "ui": "\u529f\u7387\u68c0\u6d4b\u63d2\u5ea7\u8fc7\u8f7d\u544a\u8b66", 
        "uiid": 32
      }
    }, 
    "group": "", 
    "groups": [], 
    "ip": "[hidden]" 
    "location": "", 
    "name": "[hidden]", 
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "online": true, 
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "params": {
      "alarmCValue": [
        -1, 
        -1
      ], 
      "alarmPValue": [
        -1, 
        -1
      ], 
      "alarmType": "pcv", 
      "alarmVValue": [
        -1, 
        -1
      ], 
      "controlType": 8, 
      "current": "0.15", 
      "fwVersion": "2.7.0", 
      "hundredDaysKwh": "get", 
      "init": 1, 
      "oneKwh": "stop", 
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
      "power": "21.85", 
      "rssi": -60, 
      "staMac": "xx:xx:xx:xx:xx:xx", 
      "switch": "on", 
      "timeZone": 2, 
      "voltage": "237.43"
    }, 
    "productModel": "Pow_R2", 
    "settings": {
      "alarmNotify": 1, 
      "opsHistory": 1, 
      "opsNotify": 0
    }, 
    "sharedTo": [], 
    "showBrand": true, 
    "type": "10", 
    "uiid": 32
  }, 
  {
    "__v": 0, 
    "_id": "[hidden]" 
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "brandName": "Sonoff", 
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "deviceStatus": "", 
    "deviceUrl": "", 
    "deviceid": "[hidden]" 
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "extra": {
      "_id": "[hidden]" 
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx", 
        "brandId": "58e5f344baeb368720e25469", 
        "description": "WO1851", 
        "mac": "xx:xx:xx:xx:xx:xx", 
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8", 
        "model": "PSF-BRA-GL", 
        "modelInfo": "5a2e1b360cf772f92c342f01", 
        "ui": "RFBridge", 
        "uiid": 28
      }
    }, 
    "group": "", 
    "groups": [], 
    "ip": "[hidden]" 
    "location": "", 
    "name": "[hidden]", 
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "online": true, 
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "params": {
      "cmd": "trigger", 
      "fwVersion": "2.6.0", 
      "init": 1, 
      "rfChl": 0, 
      "rfList": [
        {
          "rfChl": 0, 
          "rfVal": "331801CC0582EE4D13"
        }
      ], 
      "rfTrig0": "xxxx-xx-xxxxx:xx:xx.xxx", 
      "rssi": -38, 
      "timers": []
    }, 
    "productModel": "RF_Bridge", 
    "settings": {
      "alarmNotify": 1, 
      "opsHistory": 1, 
      "opsNotify": 0
    }, 
    "sharedTo": [], 
    "showBrand": true, 
    "tags": {
      "disable_timers": [], 
      "zyx_info": [
        {
          "buttonName": [
            {
              "0": "Button Name1"
            }
          ], 
          "name": "[hidden]", 
          "remote_type": "6"
        }
      ]
    }, 
    "type": "10", 
    "uiid": 28
  }
]`
I had to use py2.7 because it didn't want to work with 3 for some weird reason. Anyhow what are your thoughts on the dump? Thanks!

**Comment by peterbuga** [comment]
You got it this time 🙌 !

I was right, Sonoff RF was the culprit! For now I added a patch to ignore this device to stop throwing errors and you'll be able to use only the Sonoff Pow 2 switch + sensors, use the `master` branch to update the files.

As I mentioned it's the first time I'm seeing a Sonoff RF dump, and never saw it action (without youtube videos) so I guess in your case the *Wireless Door Window Detector* should work as a binary sensor inside HA  (door open or closed), right?

Will it be too much to ask to do another 2 dumps, one when you have the door open and one when you have the door closed? (put each in a file and name them accordingly). Also please tell me the name of *Wireless Door Window Detector* you have set it up in eWeLink app (i know this might sound weird but for safety reasons the `sonoff-debug` obfuscates a lot of important data and in this case i cannot find from where the name comes from)

**Comment by DenielTorres** [comment]
Works like a charm, no errors anymore! Thanks a bunch!!! 
Also, I did 2 more dumps as you asked for each state. The name is `Front Door` at least in the app, but I'm getting a feeling it's just a "friendly name" and the real one is `Button Name1` Below are the dumps:

Open
`[
  {
    "__v": 0,
    "_id": "[hidden]"
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]"
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]"
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WO1852",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSC-B67-GL",
        "modelInfo": "5a2e1ae50cf772f92c342ef6",
        "ui": "\u529f\u7387\u68c0\u6d4b\u63d2\u5ea7\u8fc7\u8f7d\u544a\u8b66",
        "uiid": 32
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]"
    "location": "",
    "name": "[hidden]",
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "alarmCValue": [
        -1,
        -1
      ],
      "alarmPValue": [
        -1,
        -1
      ],
      "alarmType": "pcv",
      "alarmVValue": [
        -1,
        -1
      ],
      "controlType": 8,
      "current": "0.16",
      "endTime": "",
      "fwVersion": "2.8.0",
      "hundredDaysKwh": "get",
      "init": 1,
      "oneKwh": "get",
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "power": "21.90",
      "rssi": -60,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startTime": "xxxx-xx-xxxxx:xx:xx.xxx",
      "switch": "on",
      "timeZone": 2,
      "voltage": "235.62"
    },
    "productModel": "Pow_R2",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "type": "10",
    "uiid": 32
  },
  {
    "__v": 0,
    "_id": "[hidden]"
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]"
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]"
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WO1851",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-BRA-GL",
        "modelInfo": "5a2e1b360cf772f92c342f01",
        "ui": "RFBridge",
        "uiid": 28
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]"
    "location": "",
    "name": "[hidden]",
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "cmd": "trigger",
      "fwVersion": "2.7.0",
      "init": 1,
      "rfChl": 0,
      "rfList": [
        {
          "rfChl": 0,
          "rfVal": "331801CC0582EE4D13"
        }
      ],
      "rfTrig0": "xxxx-xx-xxxxx:xx:xx.xxx",
      "rssi": -37,
      "sledOnline": "on",
      "timers": []
    },
    "productModel": "RF_Bridge",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "disable_timers": [],
      "zyx_info": [
        {
          "buttonName": [
            {
              "0": "Button Name1"
            }
          ],
          "name": "[hidden]",
          "remote_type": "6"
        }
      ]
    },
    "type": "10",
    "uiid": 28
  }
]
`
Closed
`[
  {
    "__v": 0,
    "_id": "[hidden]"
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]"
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]"
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WO1852",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSC-B67-GL",
        "modelInfo": "5a2e1ae50cf772f92c342ef6",
        "ui": "\u529f\u7387\u68c0\u6d4b\u63d2\u5ea7\u8fc7\u8f7d\u544a\u8b66",
        "uiid": 32
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]"
    "location": "",
    "name": "[hidden]",
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "alarmCValue": [
        -1,
        -1
      ],
      "alarmPValue": [
        -1,
        -1
      ],
      "alarmType": "pcv",
      "alarmVValue": [
        -1,
        -1
      ],
      "controlType": 8,
      "current": "0.16",
      "endTime": "",
      "fwVersion": "2.8.0",
      "hundredDaysKwh": "get",
      "init": 1,
      "oneKwh": "get",
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "power": "21.87",
      "rssi": -60,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startTime": "xxxx-xx-xxxxx:xx:xx.xxx",
      "switch": "on",
      "timeZone": 2,
      "voltage": "232.78"
    },
    "productModel": "Pow_R2",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "type": "10",
    "uiid": 32
  },
  {
    "__v": 0,
    "_id": "[hidden]"
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]"
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]"
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WO1851",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-BRA-GL",
        "modelInfo": "5a2e1b360cf772f92c342f01",
        "ui": "RFBridge",
        "uiid": 28
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]"
    "location": "",
    "name": "[hidden]",
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "cmd": "trigger",
      "fwVersion": "2.7.0",
      "init": 1,
      "rfChl": 0,
      "rfList": [
        {
          "rfChl": 0,
          "rfVal": "331801CC0582EE4D13"
        }
      ],
      "rfTrig0": "xxxx-xx-xxxxx:xx:xx.xxx",
      "rssi": -37,
      "sledOnline": "on",
      "timers": []
    },
    "productModel": "RF_Bridge",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "disable_timers": [],
      "zyx_info": [
        {
          "buttonName": [
            {
              "0": "Button Name1"
            }
          ],
          "name": "[hidden]",
          "remote_type": "6"
        }
      ]
    },
    "type": "10",
    "uiid": 28
  }
]
`
Thanks again for all the help and let me know if I can help any other way with the bridge or something else! Cheers

**Comment by peterbuga** [comment]
Thanks for the dumps and sticking around 😅 I will close this issue cuz' it's sort of fixed and I will open another one for Sonoff RF Bridge integration. 
This way I can better track them.
