### ISSUE TITLE
hass.io add-on repository

### ISSUE THREAD

**Issue by powell-christopher** [peterbuga/HASS-sonoff-ewelink#39]
Would it be possible to make this into a add-on repository for easier setup?

**Comment by peterbuga** [comment]
hi @powell-christopher 
it could be possible (after all, anything is) and yes, it might provide an easier setup but i don't plan to use a hass.io anytime soon nor spend more time debugging for this too. i'm investing quite some hours into adding new devices as it is.
i think anyone else can cut 1 minute of their time to copy-paste 3 files onto their setup if they **really** want this component in their setup or they can use other similar alternatives.

i *might* package it & submit it for the main HA repository in the future... *might*...
