### ISSUE TITLE
TH16 Sensor Readings

### ISSUE THREAD

**Issue by WeaselBreath** [peterbuga/HASS-sonoff-ewelink#45]
First, thank you for the time spent with this development.  It is very nice not to have to flash Sonoff devices that are already embedded in projects that I started using before HA.  I have three TH16's so I was eager to upgrade your files to take advantage of the temperature sensor readings from the Sonoffs.  After upgrading your python files the TH16's only take a reading for temp and humidity whenever HA is restarted.  They do not poll the temps every 60 seconds as set in my config file

###################################
#     Sonoff Switches
###################################
sonoff:
  username: !secret life360_username
  password: !secret big_little_pwd
  scan_interval: 60
  grace_period: 180
  api_region: 'us'  

Also, changing switches on Sonoff basics and TH16's in HA no longer functions.  They worked fine on previous version of your scripts before sensors were added.  I have tried reinstalling the python code several times, to make sure there is no error on my part and also deleted the __pycache__ files from all folders, no success.  The polling problem is with both temp and humidity readings so probably not a Celsius to Fahrenheit issue (my graphs in HA display the only reading they get upon restart of HA in F correctly).  I have no idea what the problem could be, waited to see if anyone else reported it, then decided to post my experience here.  I am also logged out of the eWelink app on all my devices.  

My sonoff basics are on 2.61 firmware and TH16's on 2.60 ( no update available for them yet).  HA is 0.85.1

Hope this info helps.

**Comment by peterbuga** [comment]
Hi @WeaselBreath 
sorry for the things not working out anymore :( clearly that was not the intention.

can you please specify exactly what version of the files are you using branch and/or release and by the looks of it you should most likely have some errors in the logs, please look for them it'll help me a lot to figure out the problem.

**Comment by WeaselBreath** [comment]
Peter:

Sorry for not following up sooner.  I switched from the 64 bit version of HA to the 32 bit version, added back in my config files and then added in your Sonoff add on and everything works as expected.  The temp/humidity sensors came up first, then after a couple of hard reboots of the Pi, the switches appeared.  I'm not sure if the problems I experienced are related to the 64 bit version of HA or some other config issue.  Anyhoo, thank you for the time spent on this development, I am very pleased with the ability to access my Sonoff switches/sensors w/o having to tear into projects and manually flash them.

Mark

**Comment by peterbuga** [comment]
Glad you had it working eventually, I do believe there was some configuration on your part as this component is not even near as complex to have an effect between 32/64bit of hosting system. for future reference, the switch entities are created in the same way & time like the sensors, if you keep getting one but not the other start debugging on your installation (ex: temp disable all other components/configurations)
