### ISSUE TITLE
Sonoff 1 channel inching 5V/12

### ISSUE THREAD

**Issue by warcanoid** [peterbuga/HASS-sonoff-ewelink#46]
I have succesfully added 1 channel sonoff for garage door: 
https://www.itead.cc/inching-self-locking-wifi-wireless-switch.html. Thanks @peterbuga! It worked fine on 2.6 firmware, and works now fine on 2.6.1 firmware.
But how to set the switch, to be acting like inching switch? Now when I turn on the switch it open door and stays on. To close door I must power off switch and power on again to close door and then power off at end. Any idea how to change the switch to go off by itself or act like inching?

**Comment by peterbuga** [comment]
i already replied it here 😅  https://community.home-assistant.io/t/sonoff-ewelink-component-for-original-firmware/81369/229?u=peterbuga follow the requests please
