### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by fabiosoft** [peterbuga/HASS-sonoff-ewelink#48]
How install this component inside home assistant?
I tried to add repository url but it only adds an unknown box...

**Comment by fabiosoft** [comment]
i get this error:

```
Configuration invalid
Component not found: sonoff
```

**Comment by warcanoid** [comment]
You must also add this files: 
copy the *.py files in custom_components folder using the same structure like defined here:

 custom_components
    ├── sonoff.py
    └── switch
        └── sonoff.py
    └── sensor
        └── sonoff.py

**Comment by fabiosoft** [comment]
I was not able to find the custom_components folder, so i create it and uploaded files inside.

now works, thanks.
