### ISSUE TITLE
Hassio hangs on bootup after adding the the sonoff component

### ISSUE THREAD

**Issue by peroanjo** [peterbuga/HASS-sonoff-ewelink#49]
Hi there, first of all I'd like to thank you for your work. For some reason everytime I try to add the custom component and reboot my raspberry pi 2 will hang at "starting eudev-3.2.5", if I delete the custom_components folder and delete de sonoff part of my configuration.yaml it will go back to booting perfectly. I don't know what I'm doing wrong, I created the custom_component folder with its subfolders and files on the config/ folder. I'm running hassOS 1.13. Thanks in advance.

**Comment by peroanjo** [comment]
Hi, thanks for the fast response.  After a few reboots it finally got working. I can now see my switch, however I get no response from turning it on inside home assistant while it works on the ewelink app. I've run sonoff-debug.py with this output:

```
[
  {
    "__v": 0, 
    "_id": "[hidden]", 
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "brandName": "Sonoff", 
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "deviceStatus": "", 
    "deviceUrl": "", 
    "deviceid": "[hidden]", 
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
    "extra": {
      "_id": "[hidden]", 
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx", 
        "brandId": "58e5f344baeb368720e25469", 
        "description": "WO1881977", 
        "mac": "xx:xx:xx:xx:xx:xx", 
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8", 
        "model": "PSF-B01-GL", 
        "modelInfo": "5bc48517894050613823fb90", 
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7", 
        "uiid": 1
      }
    }, 
    "group": "", 
    "groups": [], 
    "ip": "[hidden]", 
    "location": "", 
    "name": "[hidden]",, 
    "online": true, 
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx", 
    "params": {
      "bindInfos": {
        "gaction": [
          "1c917b40-9328-4983-8d29-d7705100d5d5_ewelink-google-home-v1"
        ]
      }, 
      "fwVersion": "2.6.0", 
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 
      "rssi": -76, 
      "staMac": "xx:xx:xx:xx:xx:xx", 
      "startup": "off", 
      "switch": "off"
    }, 
    "productModel": "Basic2", 
    "settings": {
      "alarmNotify": 1, 
      "opsHistory": 1, 
      "opsNotify": 0
    }, 
    "sharedTo": [], 
    "showBrand": true, 
    "type": "10", 
    "uiid": 1
  }
]
```
Also, I've attached my config folder (removing some sensitive data) just in case. Thanks in advance.

[homeassistant.zip](https://github.com/peterbuga/HASS-sonoff-ewelink/files/2804018/homeassistant.zip)

**Comment by peroanjo** [comment]
Nevermind, everything is working correctly now, I created a second account and it is working like a charm. Thank you so much for your work!

**Comment by peterbuga** [comment]
@peroanjo be sure to keep an eye on the project, there's an important update in the near future (i hope 🤞) much faster/less resource intensive and somehow more reliable ;) glad you had it working eventually!
