### ISSUE TITLE
Error while setting up platform sonoff

### ISSUE THREAD

**Issue by Jourawski** [peterbuga/HASS-sonoff-ewelink#52]
I'm using home assistant on a virtual environment. I do not see any sonoff and it appears:

Error while setting up platform sonoff
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/homeassistant/.homeassistant/custom_components/switch/sonoff.py", line 22, in async_setup_platform
    if 'switches' in device['params']:
KeyError: 'params'

What can I do? Thanks

**Comment by peterbuga** [comment]
Please enumerate what kind of devices you have, i tend to believe the error is due to some new device i might've not come across until now.

Also, i'll be better if you could follow these steps and post the output https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug

**Comment by peterbuga** [comment]
@Jourawski did you manage to get it working? if so, i would like to close this issue

**Comment by Jourawski** [comment]
How can I provide the output script?

**Comment by peterbuga** [comment]
i provided instructions in the link above :expressionless: have you even tried to read anything from it?

**Comment by Jourawski** [comment]
I saw but I had problems. I solved the problem by activating the LAN function from the eWelink app.

**Comment by peterbuga** [comment]
i have to say, it sort of makes absolutely no sense for me why activating the LAN mode changed anything in order to fix error above buuuut if it works it works i guess 👍
