### ISSUE TITLE
succes test 

### ISSUE THREAD

**Issue by mlkpo** [peterbuga/HASS-sonoff-ewelink#54]
hello, thank for your work, if this can help you. I have test with home assistant and this product

[Tishric-Basic-Smart-WIFI-Switch-10A-16A](https://www.aliexpress.com/item/Tishric-Basic-Smart-WIFI-Switch-10A-16A-Wireless-Timing-Delay-Remote-Control-Light-Switch-Sonoff-Basic/32962721558.html?spm=2114.search0104.3.16.4233143cvt5ZVQ&ws_ab_test=searchweb0_0,searchweb201602_1_10065_10068_319_10892_317_10696_10084_453_454_10083_10618_10304_10307_10820_10821_537_10302_536_10902_10843_10059_10884_10887_321_322_10103,searchweb201603_45,ppcSwitch_0&algo_expid=4b4cbd8f-a32e-4e81-8155-6f60c57e1723-2&algo_pvid=4b4cbd8f-a32e-4e81-8155-6f60c57e1723&transAbTest=ae803_3)

this is the json file :
[
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandName": "BLue50",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceUrl": "",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "593819fd98aebf3876f824f5",
        "description": "20181012002",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6c5f\u95e8\u5e02\u4e94\u5341\u5ea6\u84dd\u667a\u80fd\u79d1\u6280\u6709\u9650\u516c\u53f8",
        "model": "PSF-B01-GL",
        "modelInfo": "5a93682432e9a1626586e218",
        "ui": "\u5355\u901a\u9053\u63d2\u5ea7",
        "uiid": 1
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "alexa": []
      },
      "fwVersion": "2.6.1",
      "init": 1,
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -57,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "stay",
      "switch": "off"
    },
    "productModel": "SX1",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "type": "10",
    "uiid": 1
  }
]

Thank you again

I don't have to flash it with tasmota firmware,

**Comment by peterbuga** [comment]
i'm glad it works for you 👍 can you please leave a comment with an url to this device to be added to the confirmed list ? From the looks of it, if i'm not wrong, it's like a Sonoff Basic. thanks
