### ISSUE TITLE
Problems with HA r. 087.1?

### ISSUE THREAD

**Issue by cristrj** [peterbuga/HASS-sonoff-ewelink#58]
Hi, 
Has anybody tested sonoff configurations with the new release of HA, 0.87.1? Because HA don't reconize ittems after upgrade, in my case.
Tnxs,

**Comment by cristrj** [comment]
Sorry, it was a mistake for my part, RPI starts before router.
BTW, Is ther any advance whith the bridge integration?

**Comment by peterbuga** [comment]
> it was a mistake for my part, RPI starts before router

this could be turned in a nice safety feature: to retry getting the device list for a limited period of time like 5 or 10 minutes before giving up. could fix errors where the HA instance does not have immediate internet connection for whatever reasons

> Is ther any advance whith the bridge integration?

no
