### ISSUE TITLE
Sonoff 2 ch as 4 entities

### ISSUE THREAD

**Issue by juanmifernandez** [peterbuga/HASS-sonoff-ewelink#60]
Thanks a lot for your job. It's a fantastic component.
I've one issue: everything seems to work and the component found quickly mu devices, but It has added 4 entities for each sonoff 2ch device.
Have you seen it before?
Thanks

**Comment by peterbuga** [comment]
@juanmifernandez known behaviour (i won't go into details but **all** the sonoff devices have 4 entities/switches, they are just hidden inside the eWeLink app), this has been sort-of fixed in `websocket` branch if you want to use it.
