### ISSUE TITLE
Issues after updating to HA 0.88

### ISSUE THREAD

**Issue by GuyKh** [peterbuga/HASS-sonoff-ewelink#63]
Getting this in the logs:
`2019-02-22 09:37:15 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff.switch. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ImportError: No module named 'custom_components.sonoff.switch'; 'custom_components.sonoff' is not a package
`

Nothing has changed, maybe HA policies

**Comment by 2016for** [comment]
Please look into 0.88 breaking changes for Custom components.

So all sonoff custom component files have to be in config/custom_components/sonoff folder

So move /custom_components/sonoff.py to /custom_components/sonoff and rename to __init__.py
Rename /custom_components/sensor/sonoff.py to sensor.py and move to /custom_components/sonoff/

Similarly rename /custom_components/switch/sonoff.py to switch.py and move to /custom_components/sonoff/ 

So final file structure should be:

config/custom_components/sonoff/__init__.py (this was the main sonoff.py in custom_components folder)
config/custom_components/sonoff/sensor.py
config/custom_components/sonoff/sensor.py

**Comment by skelgaard** [comment]
have you checked out https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master-HA0.88+ ?

**Comment by GuyKh** [comment]
> have you checked out https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master-HA0.88+ ?

Thanks
Didn't notice that.
