### ISSUE TITLE
is it possible to make switch's action more fast. 

### ISSUE THREAD

**Issue by roffee9** [peterbuga/HASS-sonoff-ewelink#68]
When I click the switch button, sometime it took 2 seconds to turn on. i don't know if it's possible to make it more fast, like designated IP address or something?

**Comment by peterbuga** [comment]
try `websockets` branch

**Comment by peterbuga** [comment]
@roffee9 have you tried it ?

**Comment by roffee9** [comment]
Thanks, I tried but it didn't work so I changed to 0.88+ branch, and will check if it's better.

**Comment by peterbuga** [comment]
`websocket` is a rewritten code greatly different than (old) 0.88+ branch, and it has the ability to instantly change the state of the devices to/from HA (many users reported so!).  using the 0.88+ branch has absolutely no benefit over what you've been using until now
the bad part is that it is not optimized yet for the new HA component changes. this will be a natural update therefore i'm going to close this issue for now

**Comment by warcanoid** [comment]
@peterbuga wich websocket branch is for 0.9x better?

**Comment by peterbuga** [comment]
https://github.com/peterbuga/HASS-sonoff-ewelink/tree/websocket-HA0.88+ for now

**Comment by warcanoid** [comment]
Thank you! This one is faster than master 0.88+?
