### ISSUE TITLE
Turning on multiple switches

### ISSUE THREAD

**Issue by 2016for** [peterbuga/HASS-sonoff-ewelink#7]
Currently the switches turn on one by one with a 2 second delay for each sonoff (or outlet within each)

While using ifttt and Google Assistant, turn on all the lights works very well.

Let's see if we can figure something out.

**Comment by 2016for** [comment]
I have added them to a light group
```
light:
 - platform: group
```
Completely agree with the focus of the project towards websocket. 
Just wanted to put it out there.

**Comment by 2016for** [comment]
This is pretty much solved with the new websocket implementation! :)

**Comment by peterbuga** [comment]
i think so too, they work quite fast now. 
there might be a small delay and not all of them might switch in exactly the same time but giving the way HA toggles individual devices while in a group this is pretty much the best i can do 😃
