### ISSUE TITLE
Hassio reports invalid config

### ISSUE THREAD

**Issue by kingozone** [peterbuga/HASS-sonoff-ewelink#70]
Hassio keeps reporting invalid config with the following debug snippet from the logs:

2019-03-13 13:27:22 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/sonoff/__init__.py", line 52, in async_setup
    hass.data[DOMAIN] = Sonoff(config)
  File "/config/custom_components/sonoff/__init__.py", line 96, in __init__
    self.do_login()
  File "/config/custom_components/sonoff/__init__.py", line 162, in do_login
    self._bearer_token  = resp['at']
KeyError: 'at'

Tried to use the debug python script but getting no luck in having it actually process. What can I do to fix?

**Comment by peterbuga** [comment]
check here https://github.com/peterbuga/HASS-sonoff-ewelink/issues/66#issuecomment-469221156

**Comment by mclaudiopt** [comment]
HI.,.. I cannot setup this...after entering the config:
sonoff:
  username: '+351xxxxxx"
  password: 'xxxx'
if i check check configuratio, the system seems to get blocked seems it tries to validade the config forever.
can help?

![image](https://user-images.githubusercontent.com/48178294/54748167-c90b1580-4bc8-11e9-8678-3a619ad7f6b1.png)

**Comment by peterbuga** [comment]
@mclaudiopt 
can you confirm that your indentation is properly done inside the configuration.yaml? like this:
```
sonoff:
  username: '+351xxxxxx"
  password: 'xxxx'
```

**Comment by mclaudiopt** [comment]
hello
yes it is correct
![image](https://user-images.githubusercontent.com/48178294/54776618-69ccf580-4c08-11e9-83c9-23beb0ca1b4a.png)

now gives the following message (i copied again all files from here)
Invalid config for [sonoff]: expected a dictionary for dictionary value @ data['sonoff']. Got "username:'+xxxxxxx' password:'yyyyyy'". (See ?, line ?). Please check the docs at https://home-assistant.io/components/sonoff/

**Comment by kingozone** [comment]
Still having issues trying to get this to work when it worked properly for me about a month and a half . Here's my current config entry:

### Sonoff/eWelink Native ###
sonoff:
  username: '*******@gmail.com'
  password: '*******'
  scan_interval: 15
  grace_period: 600
  api_region: 'us'

**Comment by peterbuga** [comment]
@mclaudiopt i think you have problems editing the file, specifically with the line endings. try to install and use this instead https://www.home-assistant.io/addons/configurator/

@kingozone i need more details, no logs no help.

**Comment by kingozone** [comment]
@peterbuga it's the same error I posted in the OP. Tried different variationsf of quotes and marks to get it working but still get:

ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
hass, processed_config)
File "/config/custom_components/sonoff/init.py", line 52, in async_setup
hass.data[DOMAIN] = Sonoff(config)
File "/config/custom_components/sonoff/init.py", line 96, in init
self.do_login()
File "/config/custom_components/sonoff/init.py", line 162, in do_login
self._bearer_token = resp['at']
KeyError: 'at'

**Comment by peterbuga** [comment]
@kingozone this error (not properly catch yet) and as stated before shows up when you input wrong user/pass combination.
use this https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug to debug it on your side, if you should get some output if everything is ran as stated in the description. as a test, do a 2nd ewelink account, share a device to that and and try with that (also try not to put a password with weird characters...again **just as a test**)

**Comment by mclaudiopt** [comment]
hi. i have setuped now .
how do i know that login is sucessfull ? i have no error messages, but my King q4 does not show in entities
thank you

**Comment by kingozone** [comment]
@peterbuga yes, I have referenced that and going back to my op, I cannot get the debug to work inside Hass.io, thus repeating myself

**Comment by kingozone** [comment]
Everything was working fine until you updated the directory structure to match hassio's custom components order

**Comment by peterbuga** [comment]
@kingozone any (successful) updates regarding this problem?

**Comment by kingozone** [comment]
> @kingozone any (successful) updates regarding this problem?

Sorry for the delay, been on Vacay. Yea, it was my password, for some reason it didn't like spaces or either the $ or @ symbols I had. Once I changed it to something simpler, it works. Thanks for your assistance.

**Comment by terdmanski** [comment]
Hi 
I am trying to add my sonoff devices but there is a problem:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:326
Integration: Hass.io (documentation, issues)
First occurred: 21:44:09 (2 occurrences)
Last logged: 21:44:55

Invalid config for [http]: [sonoff] is an invalid option for [http]. Check: http->http->sonoff. (See /config/configuration.yaml, line 15).
Component error: https - Integration 'https' not found.

Here is my Config without credentials:
sonoff:
  username: email
  password: password
  scan_interval: 60 #(optional, lower values than 60 won't work anymore!)
  grace_period: 600 #(optional)
  api_region: 'eu' #(optional)
  entity_prefix: True #(optional)
  debug: False #(optional)

Here is debug file, can you help me to solve the problem?
[
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc/api/detail/5a2e1b470cf772f92c342f06_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "chipid": "00C6F730",
        "description": "20180112004",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-B01-GL",
        "modelInfo": "5a2e1b470cf772f92c342f06",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u5355\u901a\u9053\u5f00\u5173",
        "uiid": 6
      }
    },
    "family": {
      "id": "5f21ee1818492b0007b5b6c2",
      "index": 0,
      "room": {
        "id": "5f21ee1818492b0007b5b6c1"
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "gaction": [
          "77c845d5-f2f9-4e0c-bb46-c669c960f92e_ewelink-google-home-v1"
        ]
      },
      "fwVersion": "3.4.1",
      "init": 1,
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -51,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "off",
      "switch": "off",
      "version": 8
    },
    "productModel": "Touch EU",
    "settings": {
      "alarmNotify": 1,
      "appDoorbellNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "shareUsersInfo": [],
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "m_f92e_cont": "on"
    },
    "type": "10",
    "uiid": 6
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc/api/detail/5a2e1b410cf772f92c342f04_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "chipid": "009F09A7",
        "description": "20190315016",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-B04-GL",
        "modelInfo": "5a2e1b410cf772f92c342f04",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u53cc\u901a\u9053\u5f00\u5173",
        "uiid": 7
      }
    },
    "family": {
      "id": "5f21ee1818492b0007b5b6c2",
      "index": -1,
      "room": {
        "id": "5f21ee1818492b0007b5b6c1"
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "gaction": [
          "77c845d5-f2f9-4e0c-bb46-c669c960f92e_ewelink-google-home-v1"
        ]
      },
      "configure": [
        {
          "outlet": 0,
          "startup": "off"
        },
        {
          "outlet": 1,
          "startup": "off"
        },
        {
          "outlet": 2,
          "startup": "off"
        },
        {
          "outlet": 3,
          "startup": "off"
        }
      ],
      "fwVersion": "3.4.1",
      "init": 1,
      "lock": 0,
      "pulses": [
        {
          "outlet": 0,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 1,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 2,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 3,
          "pulse": "off",
          "width": 1000
        }
      ],
      "rssi": -55,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "switches": [
        {
          "outlet": 0,
          "switch": "off"
        },
        {
          "outlet": 1,
          "switch": "off"
        },
        {
          "outlet": 2,
          "switch": "off"
        },
        {
          "outlet": 3,
          "switch": "off"
        }
      ],
      "version": 8
    },
    "productModel": "T1 2C",
    "settings": {
      "alarmNotify": 1,
      "appDoorbellNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "shareUsersInfo": [],
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "ck_channel_name": {
        "0": "Balcony",
        "1": "Window"
      },
      "m_f92e_cont": "on"
    },
    "type": "10",
    "uiid": 7
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc/api/detail/5a2e1b410cf772f92c342f04_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "chipid": "0086E32B",
        "description": "WWJG001274",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-B04-GL",
        "modelInfo": "5a2e1b410cf772f92c342f04",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u53cc\u901a\u9053\u5f00\u5173",
        "uiid": 7
      }
    },
    "family": {
      "id": "5f21ee1818492b0007b5b6c2",
      "index": -2,
      "room": {
        "id": "5f21ee1818492b0007b5b6c0"
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "gaction": [
          "77c845d5-f2f9-4e0c-bb46-c669c960f92e_ewelink-google-home-v1"
        ]
      },
      "configure": [
        {
          "outlet": 0,
          "startup": "off"
        },
        {
          "outlet": 1,
          "startup": "off"
        },
        {
          "outlet": 2,
          "startup": "off"
        },
        {
          "outlet": 3,
          "startup": "off"
        }
      ],
      "fwVersion": "3.4.1",
      "init": 1,
      "lock": 0,
      "pulses": [
        {
          "outlet": 0,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 1,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 2,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 3,
          "pulse": "off",
          "width": 1000
        }
      ],
      "rssi": -52,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "switches": [
        {
          "outlet": 0,
          "switch": "off"
        },
        {
          "outlet": 1,
          "switch": "off"
        },
        {
          "outlet": 2,
          "switch": "off"
        },
        {
          "outlet": 3,
          "switch": "off"
        }
      ],
      "version": 8
    },
    "productModel": "T1 2C",
    "settings": {
      "alarmNotify": 1,
      "appDoorbellNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "shareUsersInfo": [],
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "ck_channel_name": {
        "0": "Ana",
        "1": "Tom"
      },
      "m_f92e_cont": "on"
    },
    "type": "10",
    "uiid": 7
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc/api/detail/5a2e1b470cf772f92c342f06_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "chipid": "00C70FBE",
        "description": "20180112004",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-B01-GL",
        "modelInfo": "5a2e1b470cf772f92c342f06",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u5355\u901a\u9053\u5f00\u5173",
        "uiid": 6
      }
    },
    "family": {
      "id": "5f21ee1818492b0007b5b6c2",
      "index": -3,
      "room": {
        "id": "5f21ee1818492b0007b5b6c0"
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "gaction": [
          "77c845d5-f2f9-4e0c-bb46-c669c960f92e_ewelink-google-home-v1"
        ]
      },
      "fwVersion": "3.4.1",
      "init": 1,
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -54,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "off",
      "switch": "off",
      "version": 8
    },
    "productModel": "Touch EU",
    "settings": {
      "alarmNotify": 1,
      "appDoorbellNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "shareUsersInfo": [],
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "m_f92e_cont": "on"
    },
    "type": "10",
    "uiid": 6
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceUrl": "https://eu-api.coolkit.cc/api/detail/5a2e1aee0cf772f92c342ef8_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "chipid": "00A34829",
        "description": "20180104005",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-B04-GL",
        "modelInfo": "5a2e1aee0cf772f92c342ef8",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u56db\u901a\u9053\u63d2\u5ea7",
        "uiid": 4
      }
    },
    "family": {
      "id": "5f21ee1818492b0007b5b6c2",
      "index": -4,
      "room": {
        "id": "5f21ee1818492b0007b5b6c1"
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "gaction": [
          "77c845d5-f2f9-4e0c-bb46-c669c960f92e_ewelink-google-home-v1"
        ]
      },
      "configure": [
        {
          "outlet": 0,
          "startup": "off"
        },
        {
          "outlet": 1,
          "startup": "off"
        },
        {
          "outlet": 2,
          "startup": "off"
        },
        {
          "outlet": 3,
          "startup": "off"
        }
      ],
      "fwVersion": "3.4.1",
      "init": 1,
      "lock": 0,
      "pulses": [
        {
          "outlet": 0,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 1,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 2,
          "pulse": "off",
          "width": 1000
        },
        {
          "outlet": 3,
          "pulse": "off",
          "width": 1000
        }
      ],
      "rssi": -79,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "switches": [
        {
          "outlet": 0,
          "switch": "on"
        },
        {
          "outlet": 1,
          "switch": "on"
        },
        {
          "outlet": 2,
          "switch": "on"
        },
        {
          "outlet": 3,
          "switch": "off"
        }
      ],
      "version": 8
    },
    "productModel": "4CH",
    "settings": {
      "alarmNotify": 1,
      "appDoorbellNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0,
      "wxAlarmNotify": 0,
      "wxDoorbellNotify": 0,
      "wxOpsNotify": 0
    },
    "shareUsersInfo": [],
    "sharedTo": [],
    "showBrand": true,
    "tags": {
      "ck_channel_name": {
        "0": "Home",
        "1": "Center",
        "2": "Front",
        "3": "Outlet4"
      },
      "m_f92e_cont": "on"
    },
    "type": "10",
    "uiid": 4
  }
]
