### ISSUE TITLE
Could this component support Sonoff T1 Touch 2 gang US? :(

### ISSUE THREAD

**Issue by anhtuanng98** [peterbuga/HASS-sonoff-ewelink#77]
Could this component support Sonoff T1 Touch 2C US? :(
All traditional switches in my house has 2 gangs so I do not want replace them by 3 or 1 gang.
Thank you so much!

**Comment by 2016for** [comment]
It should. There's not much difference b/w 3 gang and 2 gang Sonoff device
in terms of "backend"/"app" operation.

>

**Comment by peterbuga** [comment]
yes, it works already. just try it!
