### ISSUE TITLE
Issue removing old cache files 

### ISSUE THREAD

**Issue by Voz-DeCarabas** [peterbuga/HASS-sonoff-ewelink#80]
I'm now on HA 0.90.2 and tried changing to the new structure (after 0.88) but I'm getting errors.  I've tried clearing out the custom_components folders but there are python cache files in there and what ever I try I can't seem to get the permissions to delete them out.
I think this is my lack of skills on the OS rather than a problem with the component itself but can anyone help with some ideas on how to clean out custom_components properly?

**Comment by peterbuga** [comment]
hi @Voz-DeCarabas thanks for reaching out but first of all I would like to mention that this specific problem it's a bit out of the scope of this project.
you should google the exact version of HA you have installed (hassio/virtualenv/etc) and search this problem which is quite common. long story short you need to login as `root` and you'll be able to delete the cache files just fine

**Comment by Voz-DeCarabas** [comment]
Hi @peterbuga, yes as I said I didn’t think it was your code but I wondered if others had the same issue in the new version. I also thought I had tried as root but trying again and I’ve removed them. I’ll try reinstalling the new version when I can.  
Thanks for responding.
