### ISSUE TITLE
Sonoff 4CH pro R2, v2.7.0. Confirmed working but with an issue on interlocking mode.

### ISSUE THREAD

**Issue by krasatos** [peterbuga/HASS-sonoff-ewelink#85]
Hey there and thanks for this wonderful solution!

Device on version 2.7.0 (didnt want to upgrade as 3.0 does not show if it's working on your main page)
4 entities showed up as inteded on HA with their names all OK.

There is an issue when the module is set to interlocking mode. I will try to describa as good as possible.

- Relay A is on and i switch relay B on through HA,
  The machine works as intended,  Relay A turns off and relay B turns on on the machine.
  Both relays appear as ON on HA.
- If i turn on relay C on HA, 
  Some times the machine works as intended,  Relay A stays off , B turns off and relay C turns on 
  Some times it does not, Relay A turns on, Relays B and C stay off.
  All relays A, B and C stay on on HA. Some times Relay A turn off
- If i turn on relay D on HA random things happen depending on the previous step's state.

- In the case that all the relays are on on HA and D is actually on on the machine (the last one i switched on), if i start switching off relays one by one, the machine will go to the previous state, meaning by turning off D, C will turn on, etc.

Should i try updating the sonoffs FW? im just afraid i wont be able to use it at all afterwards :(

I am guessing i could fix it by making 4 tempalte switches that would run scripts and turn all the other three switches off before turning one on but i just wanted to bring it to your attention as i couldnt find any "interlocking mode" results on ha forums or here.

Thanks again for this great component, 
Stay safe :)

**Comment by peterbuga** [comment]
@krasatos hi there,
i have to admit this is quite a bit for me to process right now 😅 i need to take a step back and grasp the problem(s).

i'm not quite familiar with the interlocking states/usage as i never used it before, but in the same time i need a few more details about your setup: please specify exactly what branch are you using (master or websocket), what version of HA and exactly do you refer at as the *machine*. it'll be also quite helpful if you could provide the output of `sonoff-debug.py` script so that i can see exactly how your device is setup.

one last thing that's unclear for me: are the event's described above related to one another (like a flow of events) or they are separate instances of different problems?

last but not least... that's some really weird behaviour you have there 😆

**Comment by krasatos** [comment]
Hey, thanks for responding so quickly :)

So, the only things i can answer right now are that im on hass.io 0.90.1 and _machine_ = the sonoff 4ch.
The events that im describing are happening like a flow (each bullet after the previous one)

When in interlocking mode (there's a switch on the board that enables it) the sonoff only allows for one relay to be on at a time. Which means if i turn on A (by pressing the button) and then press button B, A will switch off and B will switch on.

To be honest it seems to me like the sonoff does not inform HA that it switched OFF the previous relays whenever it gets the command from HA to switch something ON. So in HA, all the previous relays are assumed On and this causes the behavior in my post above.

I will study how to, and provide the rest of the info you requested ( debug output and check if im on master or websocket - no idea)
Thanks again.

**Comment by peterbuga** [comment]
the picture starts to get a bit clear for me. out of curiosity, how fast are you doing the switching? is it under less than specified `scan_interval ` value? if not is possible that interlocking mode might work a bit different than what i assumed so far. but don't worry it'll be sorted out if it's a different flow it'll be easily replicated.
also, try also the [websocket branch](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/websocket-HA0.88+) and let me know if it's still the same

**Comment by krasatos** [comment]
I think you are right, if i wait for a while between each step of the flow described above, the status of the switches in HA refreshes at some point and reflects the true situation on the sonoff.
Which is logical since the sonoff does not inform HA when something is changed but we are scanning the sonoff for status every XX seconds. Right?

Is there a problem if i decrease `scan_interval` to less than 10 sec?
How can i see which branch im using right now? i updated after the .88 folder tree change  but i dont know which branch i used :)
Will give a try to the latest branch you linked and see how it goes.

**Comment by peterbuga** [comment]
there's no easy way to figure out on what branch you're on right now, therefore the easiest way is to remove all the component files and add them again (shouldn't be too hard right :P?)

the `websocket` branch linked above (which will be the default implementation in the near future) will *inform back* HA whenever a Sonoff device's status is changed manually or any other service making the whole experience faster (please bare in mind that Sonoff architecture is not made to toggle any settings faster then 1 (maaaaaaaybe 2) time every 1+ second.

**Comment by krasatos** [comment]
So, removed my old files and replaced them with the websocket branch.
It works like a charm!!
Very well done buddy, extremely appreciated :)
