### ISSUE TITLE
Error on loading sonoff component <!DOCTYPE html>

### ISSUE THREAD

**Issue by pafnow** [peterbuga/HASS-sonoff-ewelink#91]
Hello,
I've trying to get this component to work on my hassbian and after having to install manually the module websocket-client, I am now facing this issue in the home assistant log after a restart:

> 2019-04-15 08:55:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_component.py", line 118, in component_platform_discovered
>     await self._async_setup_platform(platform, {}, info)
>   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_component.py", line 198, in _async_setup_platform
>     self.hass, self.config, self.domain, platform_type)
>   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 208, in async_prepare_setup_platform
>     platform = loader.get_platform(hass, domain, platform_name)
>   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 102, in get_platform
>     base_paths)
>   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 183, in _load_file
>     module = importlib.import_module(path)
>   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 669, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 775, in get_code
>   File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/home/homeassistant/.homeassistant/custom_components/sonoff/sensor.py", line 7
>     <!DOCTYPE html>
>     ^
> SyntaxError: invalid syntax

I've try to run the sonoff-debug.script and I have obtained this:
```
[
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://as-ota.coolkit.cc/logo/z3NkwdtLaLMyJTxldpzvoHMtQAArify5.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WO18686",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSF-B04-GL",
        "modelInfo": "5a2e1b440cf772f92c342f05",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u4e09\u901a\u9053\u5f00\u5173",
        "uiid": 8
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": false,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "gaction": [
          "470e4e99-34e3-420a-b00b-c0d9358c2889_ewelink-google-home-v1"
        ]
      },
      "configure": [
        {
          "outlet": 0,
          "startup": "off"
        },
        {
          "outlet": 1,
          "startup": "off"
        },
        {
          "outlet": 2,
          "startup": "off"
        },
        {
          "outlet": 3,
          "startup": "off"
        }
      ],
      "fwVersion": "2.7.1",
      "init": 1,
      "partnerApikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -62,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "switches": [
        {
          "outlet": 0,
          "switch": "off"
        },
        {
          "outlet": 1,
          "switch": "off"
        },
        {
          "outlet": 2,
          "switch": "off"
        },
        {
          "outlet": 3,
          "switch": "off"
        }
      ],
      "timers": []
    },
    "productModel": "T1 3C",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "type": "10",
    "uiid": 8
  }
]
```

Any idea what could cause this issue?
Thanks,

My system health:
> arch | armv7l
> dev | false
> docker | false
> hassio | false
> os_name | Linux
> python_version | 3.5.3
> timezone | Asia/Ho_Chi_Minh
> version | 0.91.3
> virtualenv | true

**Comment by peterbuga** [comment]
you copy pasted ***wrong* the files from the browser. 
use the green button "Clone or Download > Download zip" from main project's page, remove everything you added before and use this newly downloaded files.

please close the issue when you got it fixed.

**Comment by pafnow** [comment]
It's working, indeed i downloaded single files with curl but it appeared to be not well formatted...
You're a genius (and I'm pretty stupid...)
Thanks a lot for your fast answer
