### ISSUE TITLE
New feature - Kingart-M4 - Wifi Touch Switch/Dimmer - pairing two switch with one bulb

### ISSUE THREAD

**Issue by Spacemarko** [peterbuga/HASS-sonoff-ewelink#96]
Can any1 help to ad new feature for the Kingart-M4, to be precise I want to control one bulb with two switch, is this possible?

**Comment by peterbuga** [comment]
@Spacemarko with all due respect, you are hijacking the purpose of this project. there are many many other sonoff related communities more inclined to this kind of problem. this is not a *new feature* and i explained already how this could work, not to mention that you duplicated an issue! what's wrong with you? unfortunately you leave no other option...
