### ISSUE TITLE
Demo Code

### ISSUE THREAD

**Issue by ErasmusJ** [peterbuga/HASS-sonoff-ewelink#98]
I am not a Python developer and I feel a bit lost: Could you please write a simple demo to show how to list all the devices, iterate through them and switch a device on/off.

**Comment by peterbuga** [comment]
Hi @ErasmusJ 
To answer your request I'm afraid I'm not having a positive response, I'm not planning to offer any kinda of support anytime soon, it takes quite a lot of time as it is right now. The code is available and it's a take-it-or-leave-it approach, might as well be a good opportunity to learn some python ;) 

In a while, per HomeAssistant rules I will split this package in different parts so you can use it as standalone to control various supported sonoff devices but I have no ETA for it, but it'll still be 100% python + no support.
Hope you understand ...
