### ISSUE TITLE
SSL Certificate Verify Failed SONOFF/EWELINK

### ISSUE THREAD

**Issue by edmarts** [peterbuga/HASS-sonoff-ewelink#99]
Hi! I was able to install sonoff / ewelink in my Home Assistant and the lights appeared ok. When trying to click to turn on/off nothing happens and the following error appears in the terminal:
They show the status on/off but only this, I can't change by clicking.

ERROR (Thread-2) [custom_components.sonoff] websocket error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self certificate certificate in certficate chain (_ssl.c: 1056)

**Comment by peterbuga** [comment]
@edmarts take a look at this highly similar issues https://github.com/peterbuga/HASS-sonoff-ewelink/issues/53 and https://github.com/peterbuga/HASS-sonoff-ewelink/issues/30

TL;DR if you cannot fix the certificates on your side i'm not going to disable the security check (feel free to dig into the code and find a fix, i'll be more than glad to add the solution, or disable it yourself)

**Comment by peterbuga** [comment]
@edmarts did you manage to fix the problem ?

**Comment by edmarts** [comment]
@peterbuga Yes!! I did the fix above:

https://timonweb.com/tutorials/fixing-certificate_verify_failed-error-when-trying-requests_html-out-on-mac/

Thanks!!
